### ISSUE TITLE
Repeating same snippet can jump to wrong placeholders

### ISSUE THREAD

**Issue by mg979** [hrsh7th/vim-vsnip#106]
sha: current master (845e60489de01ad3442203e452994822876aaea2)

Snippet (vim filetype):
```
	"for": {
		"description": "for ... ",
		"body": [
			"for $1",
			"\t$TM_SELECTED_TEXT$0",
			"endfor"
		],
		"prefix": [
			"for"
		]
	},
```

Test file:
```vim
fun! s:trim(params) abort
 let params = split(a:params, ',')
 return map(params, 'trim(v:val)')
endfun

fun! s:trim(params) abort
 let params = split(a:params, ',')
 return map(params, 'trim(v:val)')
endfun

fun! s:trim(params) abort
 let params = split(a:params, ',')
 return map(params, 'trim(v:val)')
endfun
```

- exec snippet at start of first function: OK
- exec snippet at start of second function: OK
- go back to first function and execute it again: WRONG

It seems to jump to the placeholders from snippets found later in the file.

![Imgur](https://imgur.com/kwwRZQk.gif)

**Comment by hrsh7th** [comment]
I will investigate it. thank you!

**Comment by hrsh7th** [comment]
I get the cause, I will consider & fix it.
