### ISSUE TITLE
<Plug>(vsnip-cut-text) normal mode mapping should behave like 'c' instead of 'd'

### ISSUE THREAD

**Issue by svermeulen** [hrsh7th/vim-vsnip#110]
Assuming the following .vimrc:

```
call plug#begin()
Plug 'hrsh7th/vim-vsnip'
call plug#end()

nmap        gs   <Plug>(vsnip-cut-text)
xmap        gs   <Plug>(vsnip-cut-text)
smap        gs   <Plug>(vsnip-cut-text)
```

If I open up a file like this:

```
^one
two
three
```

Assuming the cursor is on the first line, if I execute `cj` it results in:

```
^
three
```

If I execute `gsj` it results in:

```
t^hree
```

I think `gs` should behave more like the change operation `c`

**Comment by hrsh7th** [comment]
Thank you for your report, it reproduced!

I think the #111 solves this problem.

**Comment by svermeulen** [comment]
Brilliant.  Works great.  Thanks
