### ISSUE TITLE
Vim script interpolation

### ISSUE THREAD

**Issue by ahmedelgabri** [hrsh7th/vim-vsnip#121]
I want to know if I can call a function here or running normal commands or do anything complex? because when I tried to play with it seems that it can only do basic stuff. So I wonder if something like this is planned?

**Comment by hrsh7th** [comment]
Could you please provide a example?
Currently, I have no plan to extend Vim script interpolation.

**Comment by hrsh7th** [comment]
I try to use `${VIM:execute('map')}`.
It will insert all mapping description.
Isn't it enough?

**Comment by ahmedelgabri** [comment]
> I try to use `${VIM:execute('map')}`.
> It will insert all mapping description.
> Isn't it enough?

Yup this works, thanks

**Comment by hrsh7th** [comment]
Thank you for reporting.

I'm interested in your snippet!

**Comment by ahmedelgabri** [comment]
These are the last snippets that I need to port from UltiSnips they are heavily using Python

https://github.com/ahmedelgabri/dotfiles/blob/ef20ad2cc08aed6bb0b2b42d7b52f8a3129cba2e/roles/vim/files/.vim/ultisnips/all.snippets

Some of the Python helpers are here https://github.com/ahmedelgabri/dotfiles/blob/c0f8b0ab54278d575a6b0075a6ae85702a67f134/roles/vim/files/.vim/pythonx/helpers.py

### `box` '_A nice box with the current comment symbol_"

Example in a JavaScript file it will look like this

```js
//////////////////////////////////////////////////////////////////////
//                    SELECTED CONTENT                             //
////////////////////////////////////////////////////////////////////
```

But in shellscript file it will look like this

```sh
#####################################################################
##                    SELECTED CONTENT                             ##
#####################################################################
```

### `bbox` '_A nice box over the full width (&textwidth)_"

Same as above but fills the full `&textwidth` of the current buffer.

### `banner` "_add ascii banner_"

Example in a JavaScript file it will look like this

```js
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//                    SELECTED CONTENT
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

But in shellscript file it will look like this

```sh
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#                    SELECTED CONTENT
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### `:uuid` "'_Random UUID_"

Uses Python to inject a UUID

**Comment by hrsh7th** [comment]
The vsnip has an undocumented feature that calls `custom variable register`.

```vim
function! s:UUID(context) abort
  return system('python -c "import uuid, sys;sys.stdout.write(str(uuid.uuid4()))"')
endfunction
call vsnip#variable#register('UUID', function('s:UUID'))
```

**Comment by hrsh7th** [comment]
NOTE: The api does not stable now because the arguments are not fixed.
