### ISSUE TITLE
snippets with symbols

### ISSUE THREAD

**Issue by mg979** [hrsh7th/vim-vsnip#122]
I have this `c` snippet

```json
    "i<": {
        "description": "#include <>",
        "body": [
            "#include <$0.h>"
        ],
        "prefix": [
            "i<"
        ]
    },
```

It doesn't work with `i<` prefix, but it works with `<i` and also with `<<`.

**Comment by hrsh7th** [comment]
Thank you!

I think we should remove `\>` in the https://github.com/hrsh7th/vim-vsnip/blob/master/autoload/vsnip.vim#L118

**Comment by hrsh7th** [comment]
I will tackle it!

**Comment by hrsh7th** [comment]
Thank you for reporting.
I've fixed it.
