### ISSUE TITLE
[Bug] E5108: Error while calling lua chunk for luaeval(): [string "<VimL compiled string>"]:32: attempt to index field 'fn' (a nil value)

### ISSUE THREAD

**Issue by sophiabrandt** [hrsh7th/vim-vsnip#134]
Thank you for creating this useful plugin!

I'm currently getting the error
```
E5108: Error while calling lua chunk for luaeval(): [string "<VimL compiled string>"]:32: attempt to index field 'fn' (a nil value)
Error detected while processing function <SNR>40_on_text_changed[3]..26[21]..27[9]..<SNR>53_compute:
```
The error occurs _after_ I've called vim-vsnip via keyboard shortcut in insert mode.

NVIM v0.4.4
LuaJIT 2.0.5
on Linux

I would be thankful for any help debugging this as I'm not familiar with lua or VimScript.

**Comment by hrsh7th** [comment]
Sorry for the bug. The reason is that update the diffing modules. I reverted it.
