### ISSUE TITLE
Question: How to change the location of snipet files.

### ISSUE THREAD

**Issue by wizardofsource** [hrsh7th/vim-vsnip#135]
Hi!

I like using ~/.config as my config directory. Is it possible to change the location of snipet files from .vsnip to ~/.config/vsnip? 

Thanks.

**Comment by hrsh7th** [comment]
You can set `let g:vsnip_snippet_dir = expand('~/.config/vsnip')` in your vimrc.

NOTE: if you change the directory, you should move the snippet files manually.
