### ISSUE TITLE
Is it possible to make a key do two things

### ISSUE THREAD

**Issue by tami5** [hrsh7th/vim-vsnip#138]
Hi there, I'm using nvim_compe and I wonder is it possible to make <C-l> both confirm selection and expand snippet? 
thanks

**Comment by hrsh7th** [comment]
You can install vim-vsnip-integ.
vsnip-integ makes such thing.

**Comment by tami5** [comment]
Oh I did and I trsted but mapping c-l for confirming selection and expandimg did nothing work for me

**Comment by hrsh7th** [comment]
If vim-vsnip-integ + nvim-compe does not expand snippet when ConpleteDone, it seems a bug.

Could you provide reprodece step?

**Comment by tami5** [comment]
Sure thing I will also recheck how I setup vim-vsnip and nvim-compe. I'll get back to this later, but for now it might be a bug. 

Thanks @hrsh7th
