### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by mg979** [hrsh7th/vim-vsnip#139]
Before 2f5e5aada3905e4ddfc5be85a99850c841679f63:

![Imgur](https://imgur.com/BXqOTOc.gif)

After:
![Imgur](https://imgur.com/8dS0aLa.gif)

Snippet:
```json
    "fi": {
        "body": [
            "for (${1:size_t }${2:i}=0; ${2} < ${3:count}; ${4:${2}++}) {",
            "\t$TM_SELECTED_TEXT$5",
            "}$0"
        ],
        "description": "for loop (i)",
        "prefix": [
            "fi"
        ]
    },
```

**Comment by hrsh7th** [comment]
Thank you a lot!

I will investigate it.

**Comment by hrsh7th** [comment]
This is a hard problem... thank you!

**Comment by hrsh7th** [comment]
The integration test is very important after all...

I was sloppy work at the 2f5e5aa ...

**Comment by hrsh7th** [comment]
I've fixed in my local but the test is hard to implement.

**Comment by hrsh7th** [comment]
Anyway, I've pushed the commit for now.

Could you test with latest master?

**Comment by hrsh7th** [comment]
I added a test for it.

**Comment by mg979** [comment]
It seems to be fixed, thanks.
