### ISSUE TITLE
Parentheses and parameters not added after completion

### ISSUE THREAD

**Issue by ChrisAmelia** [hrsh7th/vim-vsnip#140]
It worked before. I'm not sure whether it is `completion-nvim`, `vim-snip`, `vim-snip-integ` or the server jdtls.
Maybe neovim itself.

**init.vim**
```vim
set runtimepath^=~/.local/share/nvim/plugged/nvim-lspconfig
set runtimepath^=~/.local/share/nvim/plugged/completion-nvim
set runtimepath^=~/.local/share/nvim/plugged/vim-vsnip
set runtimepath^=~/.local/share/nvim/plugged/vim-vsnip-integ

lua << EOF
	local nvim_lsp = require 'nvim_lsp'
	local root_pattern = nvim_lsp.util.root_pattern

	nvim_lsp.jdtls.setup{
		root_dir = root_pattern(".git", "pom.xml"),
		on_attach = require'completion'.on_attach,
	}
EOF
```

**Main.java**
```java
public class Main {
	public static void main(String[] args) {
		String foo = "Hello, World";
	}
}
```

**To Reproduce**

1. Open `Main.java` with `nvim -u init.vim Main.java`.

2. After the line containing `String foo`, type `foo.`

3. Completion menu appears then select `charAt(int index) : char` and press Enter.

![image](https://user-images.githubusercontent.com/16366403/98935194-7429ba80-24e3-11eb-9fcd-01c60e548b3d.png)

4. Parentheses nor parameters are added.

**Expected**

After pressing enter: `foo.charAt(index)` with cursor on `index`.

**Comment by hrsh7th** [comment]
@ChrisAmelia You should add `snippetSupport = true` like below.

```
	nvim_lsp.jdtls.setup{
		root_dir = root_pattern(".git", "pom.xml"),
        on_attach = require'completion'.on_attach,
        init_options = {
          usePlaceholders = true,
        }
	}
```

**Comment by ChrisAmelia** [comment]
Tried, same result.

**Comment by hrsh7th** [comment]
Oh...Soery.,It's my mistake.

You sgould add the 'snippetSipport = true'

**Comment by ChrisAmelia** [comment]
I'm not sure how I am supposed to do it. I added the two first lines but without expected results.

```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
                                                                          
local nvim_lsp = require 'nvim_lsp'
local root_pattern = nvim_lsp.util.root_pattern
                                                                          
nvim_lsp.jdtls.setup{
	root_dir = root_pattern(".git", "pom.xml"),
	on_attach = require'completion'.on_attach,
	init_options = { usePlaceholders = true, }
}

```
