### ISSUE TITLE
Vim not supported?

### ISSUE THREAD

**Issue by mg979** [hrsh7th/vim-vsnip#141]
In vim there are problems with placeholder expansion.

nvim:

![Imgur](https://imgur.com/e9Twdnw.gif)

vim:

![Imgur](https://imgur.com/lGv3y6Q.gif)

snippet:
```json
    "fp": {
        "body": [
            "for (${1:int} *p = ${2:pointer}; p < ${3:count}; p++) {",
            "\t${4}",
            "}${0}"
        ],
        "description": "for loop (pointer)",
        "prefix": [
            "fp"
        ]
    },
```

**Comment by hrsh7th** [comment]
Thank you for your report.

I forgot add the tests for vim...

My machine broken now so it takes time a bit.

**Comment by hrsh7th** [comment]
Hm... I couldn't reproduce it in vim with minimal vimrc...


(The integration tests failed with vim but it didn't relate to this problem)

**Comment by mg979** [comment]
Ok I'll investigate in my setup, thanks.

**Comment by hrsh7th** [comment]
Could you reproduce with #142 ?

**Comment by mg979** [comment]
It seems to fix it :+1:

**Comment by hrsh7th** [comment]
Thank you for confirmstion!
