### ISSUE TITLE
Support cwd/local .snippets 

### ISSUE THREAD

**Issue by tami5** [hrsh7th/vim-vsnip#145]
It would we be awesome to support local or current working directory .snippet so snippets can be specific for projects and can be easily shared with out teams.  

Thanks

**Comment by hrsh7th** [comment]
I think it should be https://github.com/hrsh7th/vim-vsnip/issues/127 but I don't know what VSCode does with `.code-snippet` file yet.

**Comment by tami5** [comment]
@hrsh7th  does this help https://github.com/rebornix/vscode-project-snippet , oh I saw #127 thought has different goal and just realized that it can include .snippets/*.json as well.
