### ISSUE TITLE
Duplicate snippets with nvim-lua/completion-nvim

### ISSUE THREAD

**Issue by heapslip** [hrsh7th/vim-vsnip#149]
I get duplicate snippets with `nvim-lua/completion-nvim`, maybe it's related to https://github.com/hrsh7th/vim-vsnip/commit/5fedeec956359d05496ad92fb6fd02231aeb4c76
What would be the best way to debug this?

**Comment by hrsh7th** [comment]
Could you provide an animated gif to explain the problem?

**Comment by heapslip** [comment]
@hrsh7th thanks for the quick reply!
Uploaded video here: https://imgur.com/a/P1E1tFg

**Comment by hrsh7th** [comment]
Could you provide the results of the below commands?

1. `:echomsg vsnip#source#filetypes(bufnr('%'))`
2. `:echomsg &filetype`

**Comment by hrsh7th** [comment]
I think your config has `let g:vsnip_filetypes.lua = ['lua']`

**Comment by heapslip** [comment]
> I think your config has `let g:vsnip_filetypes.lua = ['lua']`

Yes, that was it, sorry for the waste of time.
The README says that vsnip_filetypes is for extensions but it flew over my head.
Thanks a lot, and thanks for the project, it's awesome!
