### ISSUE TITLE
Undefined variable: prefix (?)

### ISSUE THREAD

**Issue by coxackie** [hrsh7th/vim-vsnip#152]
First of all, many thanks for your work.

 Completely noob question, trying to figure out what is going on. So, I have created a `.vsnip/tex.json` link to the `latex.json` file from the vscode extension Latex workshop. It is the one [here](https://github.com/James-Yu/LaTeX-Workshop/blob/master/snippets/latex.json), for ease of reference.

 Have set up completion via `completion-nvim`, and using `vsnip` as snippet engine - also have installed the integration. Now, when I try to autocomplete (which works fine as long as there is no snippet file), I get:
```
Error executing vim.schedule lua callback: ...lugged/completion-nvim/lua/completion/source/snippet.lua:63: Vim(let):E121: Undefined variable: prefix
```
I am not sure what the issue is, and even whether I should raise it here or with `completion-nvim` (or whether I am doing something really stupid). Any advise would be greatly appreciated.

**Comment by coxackie** [comment]
ok, I found the culprit, one of the snippets there had no "prefix". But I am still not able to get snippets expand for tex files. I use the key mappings described in the readme. They work ok, for example, for an r file, using [this](https://github.com/Ikuyadeu/vscode-R/blob/master/snippets/r-snippets.json). But, for tex files, I type the snippet name and then <C-j> in insert mode and it just skips a line.  :(

**Comment by hrsh7th** [comment]
I will improve it

**Comment by coxackie** [comment]
thanks - I appreciate that, but I am not sure what is the actual issue. It could be something wrong with the texlab client right now, because of [this](https://github.com/neovim/nvim-lspconfig/pull/503)m which could potentially get fixed by [this](https://github.com/neovim/nvim-lspconfig/pull/507). However, I am noticing the issue also with the clangd server: <C-j> does not make the snippet appear, it just changes line in insert mode. With R and Rust it works. I am using latest nightly.

**Comment by hrsh7th** [comment]
I've improved handling snippet as just ignore invalid snippet (e.g.: has no prefix, has no body etc...)

If you  still encountered this problem, I think it is not vsnip side problem maybe.

**Comment by coxackie** [comment]
many thanks - you are awesome!
