### ISSUE TITLE
[question] Simply use <Tab> for both expanding and jumping forward? 

### ISSUE THREAD

**Issue by coxackie** [hrsh7th/vim-vsnip#153]
Hi there. This is not a bug, but a question I have on the mapping configuration. I looked at your suggestion, and I was instead thinking of something like
```
" Expand or jump forward
imap <expr> <Tab>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<Tab>'
smap <expr> <Tab>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<Tab>'

" Jump backward
imap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
smap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
```
It uses tab both for expanding and jumping forward, so it requires less things to remember. But I may be missing something, since you have mapped separately for Expand and Jump forwards. Would you foresee any problem with the above configuration?

**Comment by hrsh7th** [comment]
Your example seems to good to me.

**Comment by coxackie** [comment]
ok, thanks, I was just wondering if you had something in mind, when you put more mappings. Feel free to close this whenever you want.

**Comment by hrsh7th** [comment]
Thank you.
If you want to know other mapping, feel free to send new issue.
