### ISSUE TITLE
Doesn't seem to work with completion-nvim for Windows

### ISSUE THREAD

**Issue by sp1n0r** [hrsh7th/vim-vsnip#159]
I tested all the other snippet plugins mentioned on completion-nvim. vim-vsnip is the only one I can't manage to get working.
I have the following on my init.vim
```
let g:completion_enable_snippet = 'vim-vsnip'
let g:completion_confirm_key = ",,"
```

If I enter some file, say a .html, I got no snippets. I'm on Windows, have nvim 0.5.0, lspconfig with many servers working and completion-nvim.

**Comment by hrsh7th** [comment]
Could you provide error message and configuration?

Hm... I have no windows environment...
I will setup CI to test with windows.

**Comment by sp1n0r** [comment]
It doesn't show any errors, both in nvim and in lsp.log. I'll provide the configuration

**Comment by sp1n0r** [comment]
lspconfig: https://pastebin.com/1LkSn4Em
telescopeconfig: https://pastebin.com/mvdCvdrH
init.vim: https://pastebin.com/Lh2Yi13c

**Comment by sp1n0r** [comment]
Here is a demo of my issue using an html file as example:
**Using Neosnippet**

https://user-images.githubusercontent.com/74260683/104091142-668a7a00-5273-11eb-9437-8e5ded83cd67.mp4

**Using vim-vsnip**

https://user-images.githubusercontent.com/74260683/104091155-7c983a80-5273-11eb-8307-4f434ba29486.mp4

**Comment by hrsh7th** [comment]
The neosnippet has a default snippets definituon but vsnip don't have it.

Please re-test after define snippet.

**Comment by sp1n0r** [comment]
Oh. How can I do that?

**Comment by sp1n0r** [comment]
Is it this command `let g:vsnip_filetypes = {} `? I want snippets for all filetypes available

**Comment by hrsh7th** [comment]
You can use `:VsnipOpen`.

https://github.com/hrsh7th/vim-vsnip#3-create-your-own-snippet

**Comment by sp1n0r** [comment]
I don't think I got it yet, do I have to manually define all snippets? I don't have the `:VsnipOpen` command

**Comment by sp1n0r** [comment]
This is what I want to achieve https://github.com/nvim-lua/completion-nvim#lsp-based-snippet-parsing

**Comment by hrsh7th** [comment]
hm... It's weird. If you install vsnip succesfuly, You can use the 'VsnipOpen' command.

And if you

**Comment by hrsh7th** [comment]
At least, the neosnippet items seems to come from neosnippet imstead,of LSP.

If you want to install html-snippets, You can install https://github.com/abusaidm/html-snippets via `Plug "abusaidm/html-snippts"` (it's explained in README.md)

**Comment by sp1n0r** [comment]
I want the snippets to come from LSP (LSP based snippet parsing) and to do so I have to use vim-vsnip right? I want snippets for all the servers I use

**Comment by hrsh7th** [comment]
in my knowledge, the html-language-server has no snippets (Actualy, it has snippets but it is,not,useful than your thoughts maybe).

So it does not look like a problem for me.

If you don't get the snippets with `vimls`, it will be problem.

**Comment by sp1n0r** [comment]
I read in some issues that htmls completion doesn't even work without having snippets :/

**Comment by sp1n0r** [comment]
Yeah snippets for vimls are not working either. Tried it with an if statement

**Comment by hrsh7th** [comment]
Do you see the completion menu if cursor is `<h|`?

**Comment by sp1n0r** [comment]
I see a completion menu when typing. Idk what `<h|` is

**Comment by hrsh7th** [comment]
```
set encoding=utf-8
scriptencoding utf-8

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
  PlugInstall
end

execute 'set runtimepath+=' . s:plug_dir

call plug#begin(s:plug_dir)
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
Plug 'nvim-lua/completion-nvim'
Plug 'neovim/nvim-lspconfig'
call plug#end()

set completeopt=menu,menuone,noselect

let g:completion_enable_snippet = 'vim-vsnip'
let g:completion_confirm_key = ',,'

autocmd BufEnter * lua require'completion'.on_attach()

lua <<EOF
  local capabilities = vim.lsp.protocol.make_client_capabilities()
  capabilities.textDocument.completion.completionItem.snippetSupport = true

  require'lspconfig'.vimls.setup{
    capabilities = capabilities,
  }
EOF
```

It is a minimal config.

In my environment, the snippet works fine.

1. Open vim with the above config.
2. `:set ft=vim`
3. Insert `call getbuf`
4. Select `getbufline` candidate
5. Type `,,` to expand snippet.

**Comment by sp1n0r** [comment]
It works with vimls now.

**Comment by hrsh7th** [comment]
Is there still a problem?

I think it means `The language server` x `completion-nvim` x `vim-vsnip` works fine.

**Comment by sp1n0r** [comment]
Thanks, it is now working fine for all servers minus the html one

**Comment by sp1n0r** [comment]
Here it says that snippets should work for html
https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#html

**Comment by hrsh7th** [comment]
I can't understand what you want.

The neovim lsp uses vscode-html-languageserver-bin and the server's repo doesn't have any snippets.
https://github.com/vscode-langservers/vscode-html-languageserver-bin/search?q=snippet

**Comment by sp1n0r** [comment]
What about the css one?

**Comment by sp1n0r** [comment]
Is then a way to enable both html and css completion and snippets? Even if with another plugin (closing this issue now since it works fine with the supported servers

**Comment by hrsh7th** [comment]
The vscode-css-languageserver-bin has not any snippet too.
https://github.com/vscode-langservers/vscode-css-languageserver-bin/search?q=snippet

In LSP, The `snippet` has a slightly unusual meaning.

Your `snippet` means https://github.com/abusaidm/html-snippets maybe.
If so, You can install it.

The snippet that defined in LSP is described in this animated gif.
https://user-images.githubusercontent.com/629908/90160819-3bd3ec80-ddcd-11ea-919b-577d7eb559a4.gif

**Comment by sp1n0r** [comment]
OH you have been a huge help.

**Comment by sp1n0r** [comment]
I'm not getting any html completion don't know it I'm supposed to either.

**Comment by hrsh7th** [comment]
The vscode has a built-in html extension so probably the `html-snippets` author abandoned it.

But you want to use https://github.com/abusaidm/html-snippets/blob/master/snippets/snippets.json so I suggest to install it.

You should read https://github.com/hrsh7th/vim-vsnip#features .

The vim-vsnip load snippets from VSCode extension.

**Comment by hrsh7th** [comment]
If you can't get to work LanguageServer's completion. You should open an issue to completion-nvim.

**Comment by hrsh7th** [comment]
By the way, In my environment, completion-nvim will display completion items in HTML filetype, if the line is `<h%CURSOR%`.

**Comment by sp1n0r** [comment]
Thanks for the help I have everything I need now :))

**Comment by sp1n0r** [comment]
How silly of me yeah the completion works, it's just for the snippets you usually type just `h` without the `<`
