### ISSUE TITLE
Incorrect placeholder selection

### ISSUE THREAD

**Issue by xuanduc987** [hrsh7th/vim-vsnip#16]
When the place holder has only 1 character
```
  "test": {
    "prefix": "dt",
    "body": "const { ${1:a} } = ${2:props};${0}"
  }
```
The selection expand to the beginning of line
![image](https://user-images.githubusercontent.com/1186411/70875716-46e63b00-1ffa-11ea-8e9d-77888d1ec673.png)

But if the placeholder has more than 1 character
```
  "test": {
    "prefix": "dt",
    "body": "const { ${1:name} } = ${2:props};${0}"
  },
```
It works correctly

![image](https://user-images.githubusercontent.com/1186411/70875723-4e0d4900-1ffa-11ea-804b-832976d27971.png)

**Comment by hrsh7th** [comment]
Thanks!
It reproduced.
I try to fix it.

**Comment by hrsh7th** [comment]
Thanks for your reporting.
I've fixed it.

**Comment by xuanduc987** [comment]
Thank you for your quick response
