### ISSUE TITLE
Are multiple snippets with the same prefix supported?

### ISSUE THREAD

**Issue by adrian5** [hrsh7th/vim-vsnip#160]
I have the following snippets defined:

```json
"doc": {
  "prefix": ["doc"],
  "body": ["{{< doc \"${1:file}\" >}} $0"],
  "description": "variant 1"
},
"doc (full)": {
  "prefix": ["doc"],
  "body": ["{{< doc \"${1:file}#${2:anchor}\" \"${3:link-text}\" >}} $0"],
  "description": "variant 2"
}
```

But no matter which one I select in the context menu, I always end up getting variant 1 (in my buffer). If I delete variant 1 from above snippet file, I can use the remaining variant 2 just fine.

Since there aren't many examples in the doc, I'm not sure if this is supported yet.

I'm using vim-vsnip with [completion-nvim](https://github.com/nvim-lua/completion-nvim/).

**Comment by hrsh7th** [comment]
It's disabled intentinally but I can add the flag for it.

**Comment by adrian5** [comment]
I see, I wasn't sure if it was some issue in conjunction with my particular completion plugin. Knowing that it wasn't a misconfiguration on my part is helpful already, thought having that as a feature would certainly be nice!

**Comment by hrsh7th** [comment]
Sorry. It is a my misunderstanding.

In vim-vsnip, it will treat duplicated prefix items in `vsnip#get_conplete_items()`.
But conpletion-nvim does not use it.
So when we solve it, we should fix completion-nvim.

**Comment by adrian5** [comment]
Ok, I take it this isn't straight forward to implement because completion-nvim needs to handle [multiple sources](https://github.com/nvim-lua/completion-nvim/pull/82#pullrequestreview-417701085) gracefully, where vim-vsnip could be one among many?

**Comment by hrsh7th** [comment]
I will look into it if I have a time.

**Comment by adrian5** [comment]
Ok, thanks!

**Comment by hrsh7th** [comment]
@adrian5 You can use it maybe https://github.com/nvim-lua/completion-nvim/pull/326#event-4201211378

**Comment by adrian5** [comment]
Do you think those few changes can solve my problem? What would the setting with vsnip be? (I'm an end-user, not a developer)

```viml
let g:completion_items_duplicate = {'vim-vsnip': 0}   # like this?
```

---

In case there was a misunderstanding, my problem is that:

```json
"a (first)": {
  "prefix": ["a"],
  "body": "a1",
},
"a (second)": {
  "prefix": ["a"],
  "body": "a2"
}
```

Gives me a menu that does the following:

```
a vim-vsnip a (first)    → a1 ✓ 
a vim-vsnip a (second)   → a1 ❌
```

Instead of:

```
a vim-vsnip a (first)    → a1 ✓ 
a vim-vsnip a (second)   → a2 ✓ 
```

**Comment by hrsh7th** [comment]
Sorry! I was misunderstood your mean.

we should fix completion-nvim to solve this.
I will create PR for completion-nvim

**Comment by hrsh7th** [comment]
Upstream PR has merged!
If you don't get correct result, please re-open this issue.

**Comment by adrian5** [comment]
Appears to work fine now, thank you very much!
