### ISSUE TITLE
how to activate Snippets for golang? 

### ISSUE THREAD

**Issue by rustiever** [hrsh7th/vim-vsnip#163]
cant activate Snippets,
i'm using completion-nvim engine
cannot figure out what i'm missing
please help me

**Comment by hrsh7th** [comment]
I can help you if you provide your setting.

**Comment by rustiever** [comment]
Thanks for response
what settings you want bro

**Comment by hrsh7th** [comment]
I want to look your vimrc. Thank you.

**Comment by rustiever** [comment]
before that, whether there will be any snippets or we need to configure ?

**Comment by hrsh7th** [comment]
The snippet has two meanings in the context of vsnip.

1. LSP snippet
- It will returns from `LanguageServer` e.g.`gopls`.
- For example, it can be realize `fmt.Println%CURSOR%<CR>` -> `fmt.Println("%CURSOR%")`

2. General pre-defined snippet
- If you want this, you should define this by yourselves.
- Or you can install `https://github.com/golang/vscode-go` by your favorite plugin managers.

I don't know which you want.

Please explain more detailed.

**Comment by rustiever** [comment]
I wanted pre-defined snippets, so I must install https://github.com/golang/vscode-go??

**Comment by hrsh7th** [comment]
Yes. you can install `golang/vscode-go`.

The other method is that you can define your own snippet manually.
Please read the README.md.

**Comment by rustiever** [comment]
whether I should install for the viscose or for Neovim?
like `Plug golang/vscode-go`

**Comment by hrsh7th** [comment]
Yes. You must add `Plug 'golang/vscode-go` if you want to use its snippets with vim-vsnip.

**Comment by rustiever** [comment]
> Yes. You must add `Plug 'golang/vscode-go` if you want to use its snippets with vim-vsnip.

@hrsh7th Thanks bro 
Now its working

**Comment by AvinFajarF** [comment]
> Yes. You must add `Plug 'golang/vscode-go` if you want to use its snippets with vim-vsnip.

I have installed via
Plug 'golang/vscode-go .
but when i open my main.go file my snippets doesn't work. do you have a solution?
