### ISSUE TITLE
i want use vscode-vue-snippets in 'vue' file

### ISSUE THREAD

**Issue by hamsterBiscuit** [hrsh7th/vim-vsnip#166]
i want use [vscode-vue-snippets](https://github.com/hollowtree/vscode-vue-snippets) in 'vue' file,
but is not work.

i need config something?

my config:

```
            vim.g.vsnip_filetypes = {}
            vim.g.vsnip_filetypes.javascriptreact = {"javascript"}
            vim.g.vsnip_filetypes.vue = {"vue", "javascript", "typescript"}
            vim.g.vsnip_filetypes.typescriptreact = {"typescript"}

```

**Comment by hrsh7th** [comment]
The vue files seems to have a two languageId in VSCode (vue/vue-html).
See https://github.com/hollowtree/vscode-vue-snippets/blob/master/package.json#L58 .

I don't know vim has two filetype or not.

**Comment by hamsterBiscuit** [comment]
i use [posva/vim-vue](https://github.com/posva/vim-vue) add file type
run `:echo &filetype ` output `vue`
sorry, i'm a vimer new.
if you needs more info, i have try provide you needs

**Comment by hamsterBiscuit** [comment]
i have another question，i want ts filetype use js filetype snippets,How do i set?

```
vim.g.vsnip_filetypes.typescript = {"javascript"}
```

is it right?

**Comment by hrsh7th** [comment]
It seems correct to me.
The original issue reproduced may be. I will investigate it.

**Comment by hrsh7th** [comment]
I've fixed it.

Thank you for your report!

**Comment by hamsterBiscuit** [comment]
thanks you help, it's worked for me
