### ISSUE TITLE
Getting snippets to show up when using autocomplete

### ISSUE THREAD

**Issue by CadeMichael** [hrsh7th/vim-vsnip#167]
Sorry if this is a dumb question or not related to this plugin. I have both the vsnip and vsnip-integ plugins installed and they work with clangd snippets (I am using clangd with vim-lsc) but I cannot get my custom snippets to show up in the autocomplete menu. I am missing a command or is this a feature that does not exist?

Thank you

**Comment by hrsh7th** [comment]
The vim-lsc's auto-completion is targetted to only LSP completion.
So you should use another auto-completion plugin if you want.
