### ISSUE TITLE
no snippets found, even though g:vsnip_snippet_dir is set correctly

### ISSUE THREAD

**Issue by Kristoffer-PBS** [hrsh7th/vim-vsnip#169]
I am using `nvim-compe` as a completion provider, but none of my snippets are showing up even though the `g:vsnip_snippet_dir` is set to the default one, where I have my snippets i.e. `~/.vsnip`. For example if i run `VsnipOpen` in a lua file, then the `~/.vsnip/lua.json` file is correctly found and opened.

I am using the defualt configurations as described in the `nvim-compe` README.

```lua
vim.cmd("packadd paq-nvim") -- load package

local paq = require("paq-nvim").paq -- import module and pind 'paq' function

paq { "savq/paq-nvim", opt = true } -- let paq manage itself

paq("hrsh7th/nvim-compe")
paq("hrsh7th/vim-vsnip-integ")
paq("hrsh7th/vim-vsnip")

require("compe").setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 2;
  preselect = "enable";
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;

  source = {
    path = true;
    buffer = true;
    calc = false;
    vsnip = true;
    nvim_lsp = false;
    nvim_lua = true;
    -- spell = true;
    -- tags = true;
    -- snippets_nvim = true;
    -- treesitter = true;
  };
}
```

All the other completion sources provided by `nvim-compe` works.

**Comment by hrsh7th** [comment]
Please repro steps. I can't repro it.

I have `fname` snippet as global snippet. (It will be expanded as buffer name)

It works fine in Lua filetype.

**Comment by hrsh7th** [comment]
And it looks like nvim-compe's problem. Why you open issue on vim-vsnip?

**Comment by Kristoffer-PBS** [comment]
I think I found the solution, some of my snippets in `global.json` was not formatted correctly, which caused none of the snippets to be loaded.
You can close this issue!

**Comment by Kristoffer-PBS** [comment]
I think I found the solution, some of my snippets in `global.json` was not formatted correctly, which caused none of the snippets to be loaded.
