### ISSUE TITLE
$0 doesn't work if it isn't the last item.

### ISSUE THREAD

**Issue by sigzero** [hrsh7th/vim-vsnip#17]
I have a shell script snippet defined as:

`    
"WHILE Loop with file input": {
    "prefix": "whilef",
        "body": [
            "while read f; do",
            "  $0",
            "done < ${1:file_to_read}"
        ],
        "description": "While loop with read file snippet"
    }
`

When the snippet runs, it takes me to $1 where I insert the file name and then when I tab nothing happens. 

I would expect the cursor to end up wherever the $0 is defined in the snippet.

**Comment by hrsh7th** [comment]
Oh, It is bug. Thanks!
It is not related to $0 position but it related to diff range check.

**Comment by hrsh7th** [comment]
This is critical difficult bug. Please wait.

**Comment by hrsh7th** [comment]
I finally understood the cause.
