### ISSUE TITLE
Cannot load snippet from vscode-python on Windows

### ISSUE THREAD

**Issue by jmlucjav** [hrsh7th/vim-vsnip#171]
Hi,

My env is Windows 10, running nvim head (from 5 days ago) on windows terminal.

My vim conf is:

```
Plug 'hrsh7th/nvim-compe'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
Plug 'microsoft/vscode-python'

let g:completion_enable_snippet = 'vim-vsnip'
let g:completion_confirm_key = ',,'
```

But when I open a python file, I don't get any snippet completion. I am not sure of several things:

1. is vim-vsnip-integ needed? I read in another issue it is not needed anymore but I am not sure, it is still on the README
2. do I need to do something with vscode-python, or just plug-in it is enough? I had a look and I cannot find any snippet files in there (not sure what I should be looking for either)
3. do I need to set g:vsnip_snippet_dir to something? 

thanks!

**Comment by hrsh7th** [comment]
The `vscode-python` seems to removed all bundled snippets.
https://github.com/microsoft/vscode-python/pull/15006

You can use https://github.com/ylcnfrht/vscode-python-snippet-pack instead.

**Comment by jmlucjav** [comment]
ok! but just plug-in that is not enough at least for me. Also set this:

let g:vsnip_snippet_dir = 'c:\tools\nvim\plugged\vscode-python-snippet-pack\snippets'

but still no luck

**Comment by hrsh7th** [comment]
I have no windows environment. Sorry.

Please try `let g:vsnip_snippet_dir = resolve('c:\tools\nvim\plugged\vscode-python-snippet-pack\snippets')`
if it does not work, I have no idea ...

**Comment by jmlucjav** [comment]
Ok, I got something at least.

First this works:

let g:vsnip_snippet_dir = expand('c:\\tools\\nvim\\plugged\\vscode-python-snippet-pack\\snippets')

But vscode-python-snippet-pack names the snippet file python_snippets.json, so you have to rename it to python.json (you might want to have that into account).

then, I try 
```
abs|
```
and I do C-j

I get this error:

![image](https://user-images.githubusercontent.com/1813237/107667853-4c87f100-6c90-11eb-970c-72a45071641a.png)

**Comment by hrsh7th** [comment]
No.
vsnip loads vscode plugin's snippet automatically.
So you can get snippet via `Plug 'https://github.com/ylcnfrht/vscode-python-snippet-pack'`.
If it does not work, it is a bug.

**Comment by jmlucjav** [comment]
sorry not sure what you mean. Don't you think we should leave this open, at least in case someone else has some idea?

**Comment by hrsh7th** [comment]
@jmlucjav The vim-vsnip supports VSCode extension directly.

You can load `vscode-python-snippet-pack` via `vim-plug` as the below.

```viml
Plug 'ylcnfrht/vscode-python-snippet-pack'
```

**Comment by hrsh7th** [comment]
this issue should be closed. vsnip has no problem, I think.

**Comment by jmlucjav** [comment]
I am trying to explain, that at least on windows, if you just do:

```
Plug 'ylcnfrht/vscode-python-snippet-pack'
```

and open a python file, and :VsnipOpen, and pick python, it won't load the file.

If if you add

```
let g:vsnip_snippet_dir = expand('c:\tools\nvim\plugged\vscode-python-snippet-pack\snippets')
```

it will still not load the file

If you rename c:\tools\nvim\plugged\vscode-python-snippet-pack\snippets\python_snippets.json to c:\tools\nvim\plugged\vscode-python-snippet-pack\snippets\python.json then VsnipOpen will load the python snippet file.

But then I hit the issue above, in the pic.

**Comment by hrsh7th** [comment]
In vsnip, the `snippet file` has multiple meanings.

1. user-defined snippet

This snippet will be opened by `VsnipOpen` command (because this file managed by the user)

2. plugin snippet

This would not opened by `VsnipOpen` command (because this file managed by some of the external URL)

If you want to add `vscode-python-snippet-pack` snippet as user-defined snippet, you should copy&paste it to `g:vsnip_snippet_dir`.
