### ISSUE TITLE
VSCode's built in snippets

### ISSUE THREAD

**Issue by kabouzeid** [hrsh7th/vim-vsnip#172]
This works to get VSCode's built in snippets.
Feel free to add this to the README if you like it :)

using vim-plug

```
Plug 'microsoft/vscode'
Plug g:plugs['vscode'].dir.'extensions/javascript'
Plug g:plugs['vscode'].dir.'extensions/typescript-basics'
Plug g:plugs['vscode'].dir.'extensions/cpp'
Plug g:plugs['vscode'].dir.'extensions/markdown-basics'
Plug g:plugs['vscode'].dir.'extensions/php'
Plug g:plugs['vscode'].dir.'extensions/swift'
```

**Comment by jacksonludwig** [comment]
I may be wrong but this will clone the entire vscode repo right? Not a huge issue for all but I believe there are a few repos dedicated to this, like [kitagry/vs-snippets](https://github.com/kitagry/vs-snippets). I've tried it out and it seems to work just fine.

Regardless, it seems strange to me that there is no "official" snippet repo for this project like there is with UltiSnips. Hopefully hrsh7th would consider such a thing.

**Comment by hrsh7th** [comment]
I agree with @jacksonludwig.
As might be expected, All VSCode repo is too large, I think.

But thank you for your suggestions.

**Comment by kabouzeid** [comment]
Yes, I agree that it's too large (400mb). I just found it fun/surprising that it actually works and wanted to share this. Personally I don't really mind the extra 400mb on my work machine, since it's a one time thing and I also compile the typescript, html and json lang servers from this codebase.

@jacksonludwig thanks for the snippets repo, I've been looking for something like this.
Off-topic: By any chance you don't know anything like this for VSCode's typescript, html and json lang servers? Unfortunately [these](https://github.com/vscode-langservers) that everyone refers to are outdated. For now I'm compiling them from VSCode'a source.

**Comment by jacksonludwig** [comment]
@hrsh7th It seems like someone has come along with something like I was mentioning. I've only just peeked at it, but maybe [this](https://github.com/rafamadriz/friendly-snippets) is worth adding to the readme?
