### ISSUE TITLE
Can't get snippets work when sumneko_lua server is attached.

### ISSUE THREAD

**Issue by rafamadriz** [hrsh7th/vim-vsnip#180]
I get snippets working with all lang-servers with no problem, but when it comes to lua-server there's no way I can get snippets to show up when the server is attached, if I disable the server the snippets work fine. 

I already reported this problem in [sumneko/lua-language-server issue 475](https://github.com/sumneko/lua-language-server/issues/475), I give more details there with screenshots. 

But it seems like I'm the only one with this problem **(other users have custom snippets working in lua-server)** so it may be something wrong with my config or this plugin.

I'm using vsnip with compe:
```lua
require "compe".setup {
    source = {
        vsnip = {kind = "﬌"},
}
``` 
And this is the lua server config
```lua 
local luapath = "/home/rafa/.local/share/nvim/lua/sumneko_lua"
local luabin = luapath .. "/bin/Linux/lua-language-server"

nvim_lsp.sumneko_lua.setup {
    cmd = {luabin, "-E", luapath .. "/main.lua"},
    settings = {
        Lua = {
            runtime = {
                -- Tell the language server which version of Lua you're using (most likely LuaJIT in the case of Neovim)
                version = "LuaJIT",
                -- Setup your lua path
                path = vim.split(package.path, ";")
            },
            diagnostics = {
                -- Get the language server to recognize the `vim` global
                globals = {"vim"}
            },
            completion = {snippetSupport = true},
            workspace = {
                -- Make the server aware of Neovim runtime files
                library = {
                    [vim.fn.expand("$VIMRUNTIME/lua")] = true,
                    [vim.fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true
                },
                maxPreload = 10000
            },
            telemetry = {
                enable = false
            }
        }
    }
}
``` 
Any idea of what may be wrong ? 

For other server I'm just using the default `require "lspconfig".langserver.setup {}` and it all works fine.

**Comment by hrsh7th** [comment]
You should update LSP settings and define mappings.

https://github.com/hrsh7th/nvim-compe#how-to-use-lsp-snippet

**Comment by rafamadriz** [comment]
> You should update LSP settings and define mappings.
> 
> https://github.com/hrsh7th/nvim-compe#how-to-use-lsp-snippet

Sorry, I didn't say that I'm talking about custom snippets, not the snippets that come with lua server. The snippets that come with lua server work perfectly fine when it is attached. 

My problems are with custom snippets, I have already created snippets for lua files with `:VsnipOpenEdit` but as I said before, those snippets never show up when the server is attached, but when I disable the server those snippets work just fine.

**Comment by hrsh7th** [comment]
Thank you for clarification (sorry for my poor English...)

I've fixed it in nvim-compe https://github.com/hrsh7th/nvim-compe/commit/3e567cd1407833412821b9cfb7f595eafe164e0c

**Comment by rafamadriz** [comment]
Awesome!! it is now working, thanks.
