### ISSUE TITLE
UltiSnip Integration Help

### ISSUE THREAD

**Issue by Antonio-Bennett** [hrsh7th/vim-vsnip#181]
Hi, I know this isn't exactly the UltiSnip GitHub but I've been trying to get some help. I would love to use Honza snippets since there is a wide variety and they come preinstalled for a lot of languages. I'm coming from vim-vsnip which doesn't support the snippet syntax (obv) and I'm not super knowledgeable hence the ask for help but the original code I had is 

```
 _G.tab_complete = function()
    if vim.fn.pumvisible() == 1 then
      return t "<C-n>"
    elseif vim.fn.call("vsnip#available", {1}) == 1 then
      return t "<Plug>(vsnip-expand-or-jump)"
    elseif check_back_space() then
      return t "<Tab>"
    else
      return t "<Plug>(completion_smart_tab)"
    end
  end
  _G.s_tab_complete = function()
    if vim.fn.pumvisible() == 1 then
      return t "<C-p>"
    elseif vim.fn.call("vsnip#jumpable", {-1}) == 1 then
      return t "<Plug>(vsnip-jump-prev)"
    else
      return t "<Plug>(completion_smart_s_tab)"
    end
  end
```
I thought this would map to this code below but it doesn't seem to work any ideas anyone?
```
_G.tab_complete = function()                                                                                            if vim.fn.pumvisible() == 1 then
      return t "<C-n>"
    elseif vim.api.nvim_eval([[ UltiSnips#CanExpandSnippet() ]]) == 1 then
      return vim.fn['UltiSnips#ExpandSnippetOrJump']()
    elseif check_back_space() then
      return t "<Tab>"
    else
      return t "<Plug>(completion_smart_tab)"
    end
  end
  _G.s_tab_complete = function()
    if vim.fn.pumvisible() == 1 then
      return t "<C-p>"
    elseif vim.api.nvim_eval([[ UltiSnips#CanJumpBackwards() ]]) == 1 then
      return vim.fn['UltiSnips#JumpBackwards']()
    else
      return t "<Plug>(completion_smart_s_tab)"
    end
  end
```

**Comment by hrsh7th** [comment]
Please post to ultisnips or completion-nvim...
I'm busy now so the response will be late.

**Comment by Antonio-Bennett** [comment]
Haha I did and no need to rush 🙂🙂 you can take 2 weeks if you want haha do whatever you need to do :) thanks for responding so quickly!

**Comment by Antonio-Bennett** [comment]
Gonna close the issue :) After looking over and trying to fix honestly not worth the jump and time lol just gonna stick with compe and v-snip they work the way I want! Thanks for responding earlier though!
