### ISSUE TITLE
Incorrect selection with :set selection=exclusive

### ISSUE THREAD

**Issue by francisco285** [hrsh7th/vim-vsnip#183]
With ":set selection=exclusive":

![image](https://user-images.githubusercontent.com/77457027/113520253-2718b480-9568-11eb-8ba9-159ef92a1e32.png)

If I type "bar" I will get "bare" because the last letter is not being selected:

![image](https://user-images.githubusercontent.com/77457027/113520354-e9685b80-9568-11eb-8567-b2ed468a0d36.png)

If I jump to the next placeholder, the same thing happens:

![image](https://user-images.githubusercontent.com/77457027/113520443-79a6a080-9569-11eb-8448-8cbee4b7b2d9.png)

With ":set selection=inclusive" it works correctly

I'm using Neovim 0.5 with [hrsh7th/nvim-compe](https://github.com/hrsh7th/nvim-compe) and [rafamadriz/friendly-snippets](https://github.com/rafamadriz/friendly-snippets)

**Comment by hrsh7th** [comment]
@francisco285 Thank you for your report.
I will fix it.

**Comment by francisco285** [comment]
@hrsh7th  Sorry, but after b05641c it's still selecting wrong. Visually, it looks the same as when selection is set to inclusive, but in practice it's still not selecting the last letter.

The cursor shape indicates that selection is temporarily set to inclusive:
![image](https://user-images.githubusercontent.com/77457027/113594712-72859e00-960e-11eb-8f07-0ebc331b65f9.png)

(Using the same example above) But when typing "bar" we still get "bare":
![image](https://user-images.githubusercontent.com/77457027/113594945-bd9fb100-960e-11eb-8f7e-a3924e4b30b3.png)
