### ISSUE TITLE
Snippets not recognised for elixir

### ISSUE THREAD

**Issue by Thesmader** [hrsh7th/vim-vsnip#185]
I am trying to use snippets for elixir from [here](https://github.com/florinpatrascu/vscode-elixir-snippets). I have the snippets in file `elixir.json` inside my snippets directory and using nvim-compe for completion. Snippets are neither showing up in completion nor getting expanded.

[vsnip configuration](https://github.com/Thesmader/dotfiles/blob/main/.config/nvim/plugin/vsnip.vim)
[compe configuration](https://github.com/Thesmader/dotfiles/blob/main/.config/nvim/plugin/lua/compe.lua)

**Comment by hrsh7th** [comment]
The snippet json file has comments. Sorry. I can't suppoet it, because vim's json_encode can't handle it

**Comment by Thesmader** [comment]
My bad. I should have seen that. Removed the comments. Everything works great now :rocket: . Thanks for pointing that out.
