### ISSUE TITLE
Collision with Till?

### ISSUE THREAD

**Issue by onsails** [hrsh7th/vim-vsnip#189]
When vsnip expands a snippet with a named argument, for example:
```terraform
resource "resource_name" {

}
```
where `resource_name` is a named argument, pressing any alphanumeric character should replace `resource_name` by that character. And it does that except when I type `t` which enters Till (_:h t_) mode and waits for my input to find occurence of a char to the right.
Is it possible to avoid such collision?

**Comment by hrsh7th** [comment]
I guess you have `vnoremap t` in your vimrc maybe.

Please check `:map t` results.
