### ISSUE TITLE
Escaping $ doesn't work

### ISSUE THREAD

**Issue by sigzero** [hrsh7th/vim-vsnip#19]
I have the following snippet:

`    "USAGE of function parameters": {
        "prefix": "usage",
        "body": [
            "##################################################",
            "# If the arguments passed to the script equal 0",
            "# show the usage or help for the script.",
            "##################################################",
            "if [ $# -eq 0 ]; then",
            "  ${1:#code}",
            "  exit",
            "fi"
        ],
        "description": "Show usage or help if no parameters"
    },`

The snippet expansion stops in the if statement because of the $ (i.e. $#). I tried escaping it with a slash (i.e. \$#) but that didn't work.

I see nothing in the docs that covers this.

**Comment by hrsh7th** [comment]
Thanks for yor reporting

Please try double slash to escape $.
slash is special symol in JSON and snipppet both.

**Comment by hrsh7th** [comment]
I tried to use your snippet but it is not work as expected.
fixed version is here.

```
  "USAGE of function parameters": {
    "prefix": "usage",
    "body": [
      "##################################################",
      "# If the arguments passed to the script equal 0",
      "# show the usage or help for the script.",
      "##################################################",
      "if [ \\$# -eq 0 ]; then",
      " ${1:#code}",
      " exit",
      "fi"
    ],
    "description": "Show usage or help if no parameters"
  }
```
