### ISSUE TITLE
question: How to create global snippets?

### ISSUE THREAD

**Issue by monkoose** [hrsh7th/vim-vsnip#193]
Self described title. How i can create snippets and have them in all filetypes? Like date, time etc?

**Comment by hrsh7th** [comment]
You can create global snippet by `VsnipOpen` command.

**Comment by monkoose** [comment]
Thank you for fast reply.
Do you know then why global.json snippets from https://github.com/rafamadriz/friendly-snippets doesn't work?

**Comment by hrsh7th** [comment]
This snippets colletion had set `plaintext, markdown, html, tex` for global snippets.
https://github.com/rafamadriz/friendly-snippets/blob/main/package.json#L5

You can create PR for it (I think it should be workd if you add `global`)
