### ISSUE TITLE
How to refresh snippets?

### ISSUE THREAD

**Issue by levirs565** [hrsh7th/vim-vsnip#195]
When I edit snippets using `:VsnipOpen`, the snippets is not updated automatically. How to refresh snippets?

**Comment by hrsh7th** [comment]
vsnip will refresh snippet file if you save it. So it sounds a bug to me.

**Comment by thepenguinthatwants** [comment]
I also gotten the same bug. Thought it was meant to always reopen nvim to get this working.

**Comment by eric-hansen** [comment]
Works as expected for me.  When I do `:VsnipOpen` I get a choice of editing a PHP or global vsnip file when I am on a PHP filetype buffer.  So make sure you're choosing the right, and are on the right, file type if you're editing anything besides global.

**Comment by svermeulen** [comment]
This bug still exists in commit be277461265f1e5c7db470aa479f30956597ea9e

In my case I need to explicitly call `vsnip#source#user_snippet#refresh` to get it to refresh without a full restart

**Comment by svermeulen** [comment]
I investigated it and it looks like it's due to a mismatch between buffer name of the snippets file and the value provided for `g.vsnip_snippet_dir`.   Would be nice if the library canonicalized paths when using them as keys into a cache.  For now I just worked around it in my config to ensure they match

**Comment by alextricity25** [comment]
I'm was also experiencing the same problem, but then realized my snippet file wasn't valid json. Once I fixed my JSON the snippet was available to use without having to restart neovim.
