### ISSUE TITLE
BLOCK_COMMENT_START and END both use // instead of /* */

### ISSUE THREAD

**Issue by psiho** [hrsh7th/vim-vsnip#196]
Well, the title says it all. Not sure how to set this up correctly. Works in HTML ok, but javascript, typescript... nope.

Snippet is really simple:
```
	"Wrap in comment": {
		"prefix": "wrapc",
		"body": [
			"$BLOCK_COMMENT_START \t$TM_SELECTED_TEXT $BLOCK_COMMENT_END"
		],
		"description": "wraps selected text in comment"
	},
```

**Comment by hrsh7th** [comment]
@psiho The `$BLOCK_COMMENT_START` and `$BLOCK_COMMENT_END` uses `commentstring` option.

You can set `setlocal commentstring=/*%s*/`
