### ISSUE TITLE
Is there any way to add bash command output as a snippet?

### ISSUE THREAD

**Issue by thepenguinthatwants** [hrsh7th/vim-vsnip#199]
Hi,
I was wondering if there is any way to add command output using snippet? For example how to get current date?

```
{
  "Class": {
    "prefix": ["date"],
    "body": [
      "('date +%Y-%m-%d')"
    ],
    "description": "current date."
  }
}
```

I've tried using this but it didn't work.

There seems to be for my date approach to have a way to use predefined variables. 

Tried to set on my lua configs like this.

vim.g.vsnip_extra_mapping = 'v:true'

But not really sure how to get the variables to work.

**Comment by rafamadriz** [comment]
No, you can't do that, this plugin uses the format used by vscode which is described [here](https://github.com/Microsoft/language-server-protocol/blob/main/snippetSyntax.md) and [here](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax).

To get the date use the following:
```
{
  "date": {
    "prefix": "date",
    "body": ["${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DATE}T${CURRENT_HOUR}:${CURRENT_MINUTE}:${CURRENT_SECOND}"],
  }
}
```

**Comment by hrsh7th** [comment]
You can use `$VIM` variable. see docs.
