### ISSUE TITLE
snippet showing twice

### ISSUE THREAD

**Issue by prabirshrestha** [hrsh7th/vim-vsnip#20]
Any reason why it shows the snippet twice?

And with `vsnip:class` and another one just `class`? I would like to avoid using `vsnip:....`

![image](https://user-images.githubusercontent.com/287744/71336364-ae6d2080-24fb-11ea-9dc5-8e6167ef8499.png)

**Comment by hrsh7th** [comment]
You can set the `let g:vsnip_namespace = ''`.
The `namespace` feature aims invoke the snippets as file template when open empty file.

But seems bit noisy behavior...

I'll set '' for the default value.

**Comment by prabirshrestha** [comment]
Oh ya. it was for file that is not saved yet. Make sense for it to be empty by default.

**Comment by hrsh7th** [comment]
Thanks for your advice.
I remove the default value in #21.
