### ISSUE TITLE
When jumping to the next placeholder, the text of the previous placeholder is removed

### ISSUE THREAD

**Issue by YorickPeterse** [hrsh7th/vim-vsnip#200]
When using `<Plug>(vsnip-jump-next)` to jump to the next placeholder, the text of a placeholder is removed unless you edited it. This can be seen in this recording:

[![asciicast](https://asciinema.org/a/OvslmuErb2tpP3CHVRWnI0OpA.svg)](https://asciinema.org/a/OvslmuErb2tpP3CHVRWnI0OpA)

This is a bit annoying if the placeholder text already is what you were going to type (e.g. a variable name that is defined and you want to use it). In this case you have to type the same, _then_ jump to the next placeholder.

Is there a way to retain the placeholder text when jumping?

**Comment by hrsh7th** [comment]
I can't reproduce it. the expected behavior is as you said.

Could you please provide your config?

**Comment by YorickPeterse** [comment]
@hrsh7th 

I can reproduce this using the following configuration (saved in `/tmp/test.vim`):

```vim
packadd vim-vsnip " make sure this is in your package path somewhere

let g:vsnip_snippet_dir = expand('/tmp/snippets')

imap <expr> <C-s> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-s>'
imap <expr> <C-j> vsnip#jumpable(1) ? '<Plug>(vsnip-jump-next)' : '<C-j>'
```

Then create `/tmp/snippets/ruby.json`

```
{
    "def": {
        "description": "Inserts a new method",
        "body": [
            "# ${2:Description of this method.}",
            "def ${1:method_name}",
            "\t${0}",
            "end"
        ],
        "prefix": [
            "def"
        ]
    }
}
```

Then run `nvim -u /tmp/test.vim /tmp/test.rb`. In the buffer, type `def` then press `Control-s` to expand the snippet. If you now jump to the next snippet using `Control-j`, the placeholder text is removed:

[![asciicast](https://asciinema.org/a/zAZ265peD4qRDddwshnjp50ds.svg)](https://asciinema.org/a/zAZ265peD4qRDddwshnjp50ds)

**Comment by hrsh7th** [comment]
@YorickPeterse 
Could you try with the following mapping?

```
imap <expr> <C-s> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-s>'
imap <expr> <C-j> vsnip#jumpable(1) ? '<Plug>(vsnip-jump-next)' : '<C-j>'
smap <expr> <C-s> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-s>'
smap <expr> <C-j> vsnip#jumpable(1) ? '<Plug>(vsnip-jump-next)' : '<C-j>'
```

**Comment by YorickPeterse** [comment]
@hrsh7th Ah, that seems to do the trick. Looking at the ready there are `smap` lines mentioned, but it's not immediately obvious they are required to get this behaviour; but thanks for the help! :smiley:
