### ISSUE TITLE
How to format the reference?

### ISSUE THREAD

**Issue by singlexyz** [hrsh7th/vim-vsnip#209]
```json
"useState": {
  "prefix": ["us"],
  "body": [
    "const [$1, set${1}] = useState($0)"
  ]
},
```

For example, when I typing `count` in `$1` position,
it will auto format in `${1}`, like `uppercase`, `capitalize`
Maybe like this:
```json
"body": [
  "const [$1, set${1:uppercase}] = useState($0)"
]
```

**Comment by itscarlosecp** [comment]
I have a similar question to this one. I want to convert some text into uppercase, in my case is the following: `"${TM_FILENAME/(.*)/${1:/upcase}/}"`. These is one of the examples shown in the snippet [syntax documentation](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax) on the official vscode website. Does vsnip supports this feature?

**Comment by singlexyz** [comment]
Similar to https://github.com/hrsh7th/vim-vsnip/issues/83
