### ISSUE TITLE
How do I check the status of VSnip?

### ISSUE THREAD

**Issue by Melkster** [hrsh7th/vim-vsnip#211]
I've recently switched from [coc.nvim](https://github.com/neoclide/coc.nvim) to Neovim's built-in LSP, as well as from the statusline plugin [vim-airline](https://github.com/vim-airline/vim-airline) to [feline.nvim](https://github.com/famiu/feline.nvim/). I would now like to replicate how [coc-snippets](https://github.com/neoclide/coc-snippets) shows the text `SNIPPET` in the statusline (with vim-airline) when inside an active snippet.

How do I check whether or not VSnip is currently active, i.e. if I'm inside a snippet?

**Comment by hrsh7th** [comment]
@Melkster You can check `!empty(vsnip#get_context())
