### ISSUE TITLE
Snippets without alphanumeric characters in prefix don't work

### ISSUE THREAD

**Issue by haffla** [hrsh7th/vim-vsnip#213]
Hi,

I am trying to get something like this work.

```json
{
        "render": {
                "prefix": "=",
                "body": [
                        "<%= $1 %>"
                ],
                "description": "render"
        }
}
```

But when I type `=` the snippet is not suggested. Is this intended? I know it's something in https://github.com/hrsh7th/vim-vsnip/blob/master/autoload/vsnip/source.vim. But my vimscript and general vim internals knowledge is too bad.

**Comment by hrsh7th** [comment]
What does `suggest` mean? You are saying to `does not complete`, right?

I don't know what is completion engine you are using.

**Comment by haffla** [comment]
Yes exactly, I mean it's not completing. I am using hrsh7th/nvim-compe. So you think the problem is in the completion engine?

**Comment by hrsh7th** [comment]
Yes. But you should use nvum-cmp.
