### ISSUE TITLE
Not able to define mappings without Plug package manager

### ISSUE THREAD

**Issue by ITHDevelopment** [hrsh7th/vim-vsnip#216]
Package manager: Packer.nvim
Intention: Set keymappings to jump foward and backward
Problem: Mappings depend on <**Plug**> prefix
```
imap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
smap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
imap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
smap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
```
Need help, really like the plugin over others written in lua or python, I don't really want to migrate to Ultisnipts even though it's a great plugin.

**Comment by initial1ze** [comment]
`<Plug>` here does not mean it's vim-plug plugin manager, here is a screenshot from `:h Plug`.

![Screenshot from 2021-09-23 09-56-50](https://user-images.githubusercontent.com/68731452/134454612-608da6f0-fc67-4bff-a743-f62eda3eaba9.png)
 
Mappings provided in the README should work fine. If they are still not working for you, you can try and change them and see if that works.
