### ISSUE TITLE
Selection always miss the last character

### ISSUE THREAD

**Issue by AgentCosmic** [hrsh7th/vim-vsnip#222]
For example:
```
for (let index = 0; index < array.length; index++) {
	const element = array[index];
	
}
```
My first selection will be `inde`, but not `index`. Then I jump to next position `arra`, again missing the `y`.
I'm using it with nvim-cmp. Neovim 5.1 Windows.

**Comment by AgentCosmic** [comment]
Hello, is there anything I can help you to debug this more easily?

**Comment by JimmyHuang454** [comment]
Same issuse happens to me. vim8.2 in Windows.

```json
{
  "Class": {
    "prefix": ["let"],
    "body": [
      "let ${1:name} = $0"
    ]
  }
}

```

After triggered:
![搜狗截图20211218230044](https://user-images.githubusercontent.com/80503972/146645532-cdbd4a06-b933-4707-a38e-e2fae984bf4c.png)

Expect:
![搜狗截图20211218230222](https://user-images.githubusercontent.com/80503972/146645563-10a18572-60d0-46f2-8d36-b3ec8866edf0.png)

**Comment by hrsh7th** [comment]
@JimmyHuang454 I think the `name` will replace to `a` If you press `a` with `After triggered:` condition. If so It's expected behavior.

**Comment by JimmyHuang454** [comment]
I am new to vsnip, just starting in today. And I just want vsnip work as ultisnips:
![动画](https://user-images.githubusercontent.com/80503972/146648841-794ddb14-d518-44b2-90b0-3a321cfbe32f.gif)

the first `let` in the gif is triggered by vsnip, the second one is triggered by ultisnips.

My vimrc:
```viml
Plug 'hrsh7th/vim-vsnip'

let g:vsnip_snippet_dir = 'D:/Vim/test_snip'

" Expand or jump
imap <expr> <C-l>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'
```
