### ISSUE TITLE
Support snippet files with comments

### ISSUE THREAD

**Issue by smackesey** [hrsh7th/vim-vsnip#231]
It's nice that this plugin supports VSCode snippet format, but the fact that VSnip chokes on JSON comments means that you can't necessarily use the same snippet definition files (VSCode snippet files do support comments).

I see in #185 that you've said comments won't be supported since Vim `jsondecode` doesn't handle them. But it seems to me the additional support is trivial-- just strip out lines that start with "//" before passing to `jsondecode`. Just one line in vsnip#source#create should strip out comments:

```
call filter(l:file, { _, ln -> match(ln, '\v^\s*//') == -1 })
```

Unless there is some reason this is more complicated than I realize, I'd submit a PR for this.

**Comment by hrsh7th** [comment]
If the snippet body contains `//`, this patch will break everything. I can't accept it.

**Comment by smackesey** [comment]
Ah, yeah I should've thought of that. OK.
