### ISSUE TITLE
vsnip not working after upgrade to neovim 0.5.1

### ISSUE THREAD

**Issue by phuongthuan** [hrsh7th/vim-vsnip#233]
Hi guys, 

`neovim-cmp` and `vim-vsnip` are awesome plugins 🥇 . These pairs work very perfectly. I'm using it every day to speed up my coding time. I really love them ❤️ 

Today I just updated my neovim to 0.5.1 then my `vsnip` is not work anymore in javascript file.

Basically when I open to edit a javascript snippet file with `:VsnipOpen<CR>` . It shows an error like the below:

![image](https://user-images.githubusercontent.com/20045189/143542250-dc6d133a-60c1-4b36-82c3-dc9201075cde.png)

I just walk around check some changelog and breaking changes and I updated my config like this:

Here is my config:

`vsnip.lua`
```
map('n', '<leader>V', ':VsnipOpen<CR>')

cmd [[
  let g:vsnip_snippet_dir = expand('~/.vsnip') => I stored all my snippets in this folder. After upgrade to the neovim 0.5.1, I added this line
  let g:vsnip_filetypes = {}
  let g:vsnip_filetypes.javascriptreact = ['javascript']
  let g:vsnip_filetypes.typescriptreact = ['typescript']
  imap <expr> <C-l>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'
  smap <expr> <C-l>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'
]]
```
`cmp.lua`
```
    snippet = {
        expand = function(args)
            vim.fn["vsnip#anonymous"](args.body)
        end
    },
```
In Lua file, the snippet still work but I cannot use `<Tab>`

```
        ['<Tab>'] = function(fallback)
            if cmp.visible() then
                cmp.select_next_item()
            elseif vim.fn['vsnip#available']() == 1 then
                vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Plug>(vsnip-expand-or-jump)', true, true, true), '')
            else
                fallback()
            end
        end
```
How can I fix this? Thanks

**Comment by hrsh7th** [comment]
What is the `Autostart for efm failed`?

**Comment by phuongthuan** [comment]
I don't know what is it. That's my concern.

**Comment by Shougo** [comment]
It seems efm LSP warning message

**Comment by hrsh7th** [comment]
At least vim-vsnip doesn't have the code to print that error.
Perhaps your vimrc contains `require('lspconfig').efm.setup {...}`. Please review the settings again.

**Comment by hrsh7th** [comment]
https://github.com/neovim/nvim-lspconfig/blob/29dbd9fa74622338f62f0bebce7b5ce6a2138d3c/lua/lspconfig/configs.lua#L107

This message will printed by nvim-lspconfig.

I haven't recently made any of these related fixes to vim-vsnip.
