### ISSUE TITLE
need an option to easily integrate friendly-snippets into vsnip for editing them and watch VsnipOpen and etc

### ISSUE THREAD

**Issue by user84441** [hrsh7th/vim-vsnip#234]
This option didn't work for me, 
`let g:vsnip_snippet_dirs = ['/home/user/.config/nvim/plugged/friendly-snippets/snippets/', '/home/user/.config/nvim/plugged/friendly-snippets/snippets/javascript']`

**Comment by hrsh7th** [comment]
I can't understand this issue.

**Comment by user84441** [comment]
> ###

I have installed [Plug 'rafamadriz/friendly-snippets'
](https://github.com/rafamadriz/friendly-snippets)
And for example i want modify them or just watch available snippets with VsnipOpen.
I have tried speciy the path:
`let g:vsnip_snippet_dirs = ['/home/user/.config/nvim/plugged/friendly-snippets/snippets/', '/home/user/.config/nvim/plugged/friendly-snippets/snippets/javascript']`
But multiple folders don't work.

**Comment by user84441** [comment]
> I can't understand this issue.

Sorry for this issue, i have just created links to the snippets)
