### ISSUE TITLE
cant update

### ISSUE THREAD

**Issue by bryant-the-coder** [hrsh7th/vim-vsnip#241]
![image](https://user-images.githubusercontent.com/92417638/148625789-e00a72a0-9697-48b1-abb5-c2b3c39a7336.png)
i cant update vim-vsnip

**Comment by Shougo** [comment]
You should reinstall vim-vsnip by packer.

**Comment by devkvlt** [comment]
@Shougo not possible with vim-plug?

**Comment by Shougo** [comment]
vim-plug does not support reinstall.  You need to remove the plugin and install it manually.
dein.vim support the feature instead.

**Comment by Artturin** [comment]
i get such errors too, i think its because someone is using force push
```
 ✗ Failed to update hrsh7th/vim-vsnip
  Errors:
    fatal: Not possible to fast-forward, aborting.
    fd13f3f
```

**Comment by bryant-the-coder** [comment]
if you're using packer, remove amd reinstall it

**Comment by Artturin** [comment]
I know but this shouldn't be happening in the first place.

**Comment by bryant-the-coder** [comment]
i m also aware of it

**Comment by bvtthead** [comment]
vim-plug tells you what to do with
```
:PlugStatus
```
If it detects an issue you can reinstall with:
```
:PlugClean
:PlugUpdate
```
