### ISSUE TITLE
Bug: this shows up in cmdline

### ISSUE THREAD

**Issue by bryant-the-coder** [hrsh7th/vim-vsnip#242]
![image](https://user-images.githubusercontent.com/92417638/150304543-c39eb231-181a-4d31-8c33-59ebdd813535.png)
what is this? i get it everytime i start neovim. it is kinda annoying so pls help.

**Comment by bryant-the-coder** [comment]
i did. i use vsnip edit...

**Comment by bryant-the-coder** [comment]
> You should crean up your `g:vsnip_snippet_dir` files.

how?

**Comment by hrsh7th** [comment]
I don't check your conf.
I gess you have invalid snippet json file.
