### ISSUE TITLE
Can't use 'j' or 'k' when in placeholder

### ISSUE THREAD

**Issue by jkunlin** [hrsh7th/vim-vsnip#243]
The neovim will be in the select-mode when I am in the placeholder.  In this case, 'j' or 'k' can not be used as typing.

**Comment by Shougo** [comment]
I think the keys are mapped.
:verbose xmap j

**Comment by jkunlin** [comment]
> I think the keys are mapped. :verbose xmap j

You are correct. Thanks a lot.
I have a keymap like this: noremap <silent> <expr> j (v:count == 0 ? 'gj' : 'j')

Is there any way to make it compatible with this plugin?

**Comment by Shougo** [comment]
You should use nnoremap instead of noremap.

**Comment by jkunlin** [comment]
> You should use nnoremap instead of noremap.

It works. Thank you！
