### ISSUE TITLE
vsnip has support telescope.nvim to pick all vsnip used snippets?

### ISSUE THREAD

**Issue by xfyuan** [hrsh7th/vim-vsnip#247]
I use vsnip and telescope plugin together. But it seems that there's no built-in telescope picker to select the snippets(like friendly-snippets).

Does vsnip has support telescope.nvim to pick and preview all vsnip used snippets? Or is there any other way to do that?

Thanks.

**Comment by hrsh7th** [comment]
You can use `vsnip#get_completed_items(bufnr)` for listing.
And if you want to expand selected snippet, you can use `vsnip#anonymous(snippet_text)`.

**Comment by hrsh7th** [comment]
I don't plan to support telescope natively. You should implement it by yourself if you want.

**Comment by xfyuan** [comment]
Got it. Thank you.
