### ISSUE TITLE
Selection could be broken when selection is exclusive

### ISSUE THREAD

**Issue by chemzqm** [hrsh7th/vim-vsnip#249]
Bug with https://github.com/hrsh7th/vim-vsnip/blob/7fde9c0b6878a62bcc6d2d29f9a85a6616032f02/autoload/vsnip/session.vim#L133

When using `set selection=exclusive` with snippet `${1:FOO}\n${2:bar}` will result `oo\n` selected.

The fix on coc.nvim https://github.com/neoclide/coc.nvim/commit/f3022726153a67e245ac8879d9b5f431a1664e95

**Comment by hrsh7th** [comment]
Thank you. I'll look into it!

**Comment by hrsh7th** [comment]
I've fixed https://github.com/hrsh7th/vim-vsnip/commit/7a817cd9dd457b4bedb0dc0e9dc57d084ce48bab
