### ISSUE TITLE
Add default $0 tabstop if not defined

### ISSUE THREAD

**Issue by thomasfaingnaert** [hrsh7th/vim-vsnip#25]
Some language servers do not explicitly add a `$0` to the end of snippets (say, clangd).

Maybe we can add a `$0` at the end if the snippet doesn't contain a `$0` at another place?
This is also the approach taken by UltiSnips (https://github.com/SirVer/ultisnips/blob/dc9d8f5e16a0a0727a47309e6c9e9ded26bc3e0e/doc/UltiSnips.txt#L1045-L1046).

**Comment by hrsh7th** [comment]
Thanks for your feedback.
I think it is already supported in here https://github.com/hrsh7th/vim-vsnip/blob/master/autoload/vsnip/session.vim#L42 .

...ah, I understood.
The implementation is not enough when snippet has $1.

OK, I will support it.

**Comment by hrsh7th** [comment]
Fixed in https://github.com/hrsh7th/vim-vsnip/commit/5fca53ef410c9c1abb65369934da1f740628c8b9
