### ISSUE TITLE
TAB jump no longer works after selecting completion with special chars

### ISSUE THREAD

**Issue by mikehaertl** [hrsh7th/vim-vsnip#251]
I use vim-vsnip in combination with nvim-cmp and found that sometimes when I'm in a snippet and use a completion with special chars the snippet gets deactivated. So I can no longer use e.g. `<TAB>` for `vsnip-jump-next`.

Here's an example:

![vsnip-tab-issue](https://user-images.githubusercontent.com/675062/176966293-e0d21168-e39d-4440-a8f4-fd5b023eff01.gif)

* The first snippet works: I select `crypto` and then press `<TAB>` to jump to the next snippet location and can enter `sign`
* At the second snippet I select `class-validator` and then `<TAB>` inserts a `TAB` character. I can no longer navigate to the next snippet location.

This also seems to happen if I insert a CamelCase word.

I use the recommended mappings for vsnip and don't have any mappings for `<TAB>` in `nivm-cmp`. 

```vim
Plug 'hrsh7th/nvim-cmp'             " Autocomplete
Plug 'hrsh7th/cmp-vsnip'            " vsnip completion source for nvim-cmp
Plug 'hrsh7th/vim-vsnip'            " Snippets plugin
Plug 'rafamadriz/friendly-snippets', { 'branch': 'main' } " Snippets collection
" ...
imap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)' : '<Tab>'
imap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)' : '<Tab>'
smap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)' : '<Tab>'
smap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)' : '<Tab>'

```

**Comment by hrsh7th** [comment]
It is not enough information to reproduce issue.
Could you provide the your snippet? (maybe `import statements` snippet).

**Comment by mikehaertl** [comment]
The snippet is from the `rafamadriz/friendly-snippets` collection. It's nothing special:

https://github.com/rafamadriz/friendly-snippets/blob/57274f4d87b9ccb961092b25560ba300f691e943/snippets/javascript/javascript.json#L668-L671

Below you find my minimum config that should reproduce the issue.

The recipe:

```
# Volar LSP required for Javascript
sudo npm install -g volar

mkdir test
cd test
npm init -y
npm install class-validator crypt
touch x.js
vi x.js
```

* Type `imp` and the completions should come up
* Select `import statement~           Snippet`
* The cursor should now be between the double quotes of the inserted import statement
* Type `cla` and the completions should come up
* Select `class-validator`
* Now press `TAB`

The cursor should jump to the next snippet position but instead it inserts a TAB character.

You can try the same with the `crypt` library. Here the TAB key works as expected.

```
call plug#begin(stdpath('data') . '/plugged')
Plug 'junegunn/vim-plug'
Plug 'neovim/nvim-lspconfig'        " Start LSP server on demand
Plug 'hrsh7th/nvim-cmp'             " Autocomplete
Plug 'hrsh7th/cmp-nvim-lsp'         " LSP completion source for nvim-cmp
Plug 'hrsh7th/cmp-vsnip'            " vsnip completion source for nvim-cmp
Plug 'hrsh7th/vim-vsnip'            " Snippets plugin
Plug 'rafamadriz/friendly-snippets', { 'branch': 'main' } " Snippets collection
call plug#end()

" nvim-cmp Plugin settings {{{
lua <<EOF
  local cmp = require'cmp'
  cmp.setup({
    snippet = {
      expand = function(args)
        -- We use vim-vsnip
        vim.fn["vsnip#anonymous"](args.body)
      end,
    },
    mapping = {
      -- Navigate up/down (i, c: insert & command line mode)
      ['<C-j>'] = cmp.mapping(cmp.mapping.select_next_item(), {'i', 'c'}),
      ['<C-k>'] = cmp.mapping(cmp.mapping.select_prev_item(), {'i', 'c'}),
      ['<CR>'] = function(fallback)
        -- Don't block <CR> if signature help is active
        -- https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/issues/13
        if not cmp.visible() or not cmp.get_selected_entry() or cmp.get_selected_entry().source.name == 'nvim_lsp_signature_help' then
          fallback()
        else
          cmp.confirm({
            -- Replace word if completing in the middle of a word
            -- https://github.com/hrsh7th/nvim-cmp/issues/664
            behavior = cmp.ConfirmBehavior.Replace,
            -- Don't select first item on CR if nothing was selected
            select = false,
          })
        end
      end
    },
    sources = cmp.config.sources({
      { name = 'nvim_lsp' },
      { name = 'vsnip' },
    }),
  })

local lspconfig = require'lspconfig'
local cmp_nvim_lsp = require'cmp_nvim_lsp'
local util = lspconfig.util
util.default_config = vim.tbl_extend(
  "force",
  util.default_config,
  {
    -- Required by nvim-cmp
    capabilities = cmp_nvim_lsp.update_capabilities(vim.lsp.protocol.make_client_capabilities()),
  }
)
:- Helper method for volar to find tsserverlibrary by traversing parent directories.
-- If no lib found a default (i.e. global) path is returned
local function get_typescript_server_path(root_dir)

  local global_ts = '/usr/local/lib/node_modules/typescript/lib/tsserverlibrary.js'
  local found_ts = ''
  local function check_dir(path)
    found_ts =  util.path.join(path, 'node_modules', 'typescript', 'lib', 'tsserverlibrary.js')
    if util.path.exists(found_ts) then
      return path
    end
  end

  if util.search_ancestors(root_dir, check_dir) then
    return found_ts
  else
    return global_ts
  end
end
lspconfig.volar.setup{
  filetypes = {'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue', 'json'},
  on_new_config = function(new_config, new_root_dir)
    new_config.init_options.typescript.serverPath = get_typescript_server_path(new_root_dir)
  end,
}

EOF
" jump to next/prev placeholder when in vsnip template
imap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)' : '<Tab>'
imap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)' : '<Tab>'
" jump to next/prev placeholder when in vsnip template
smap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)' : '<Tab>'
smap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)' : '<Tab>'

```

**Comment by mikehaertl** [comment]
@hrsh7th Do you maybe have some tip how I could debug this? The bug makes the plugin basically unusable for me. I've looked into the vsnip sources a little but it's not so easy to follow.

Obviously `vsnip#jumpable(1)` returns falsey when it should not. I've added some debug output:

```
function! vsnip#jumpable(...) abort
  let l:direction = get(a:000, 0, 1)
  echomsg 'empty:' empty(s:session)
  ...
```

It gives me a `empty: 1` whenever I complete a more complex string like `@nestjs/cli`. So somehow `s:session` is reset - but I couldn't figure out why or where. I'm not even sure what a "Session" in this context means.

To me ot seems like it has to do with non-alphanumeric characters in `nvim-cmp` completion suggestions. Sometimes it works, sometimes it doesn't.

**Comment by hrsh7th** [comment]
Sorry. I try to your reproduce step. But I couldn't run vue-language-server. Could you re-check reproduce steps?

Addition, I don't reproduce with my daily-driver configuration.
I tried to same operation with typescript-language-server and key-mappings and snippets. But It works as expected...

**Comment by mikehaertl** [comment]
@hrsh7th Here's a reduced config. We don't even need LSP. 

Btw my version is neovim 0.7.2.

```vim
call plug#begin(stdpath('data') . '/plugged')
Plug 'junegunn/vim-plug'
Plug 'hrsh7th/nvim-cmp'             " Autocomplete
Plug 'hrsh7th/cmp-vsnip'            " vsnip completion source for nvim-cmp
Plug 'hrsh7th/vim-vsnip'            " Snippets plugin
Plug 'rafamadriz/friendly-snippets', { 'branch': 'main' } " Snippets collection
call plug#end()

lua <<EOF
  local cmp = require'cmp'
  cmp.setup({
    snippet = {
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body)
      end,
    },
    mapping = {
      ['<C-j>'] = cmp.mapping(cmp.mapping.select_next_item(), {'i', 'c'}),
      ['<C-k>'] = cmp.mapping(cmp.mapping.select_prev_item(), {'i', 'c'}),
      ['<CR>'] = function(fallback)
        if not cmp.visible() or not cmp.get_selected_entry() or cmp.get_selected_entry().source.name == 'nvim_lsp_signature_help' then
          fallback()
        else
          cmp.confirm({
            behavior = cmp.ConfirmBehavior.Replace,
            select = false,
          })
        end
      end
    },
    sources = cmp.config.sources({
      { name = 'vsnip' },
    }),
  })

EOF

" jump to next/prev placeholder when in vsnip template
imap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)' : '<Tab>'
imap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)' : '<Tab>'
" jump to next/prev placeholder when in vsnip template
smap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)' : '<Tab>'
smap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)' : '<Tab>'
```

Now try this:

![vim-cmp-vsnip](https://user-images.githubusercontent.com/675062/185669683-ed9ca580-6f24-490d-bc6e-b6de8f5e8ce9.gif)

 * `vi x.js`
 * type `i` for insert mode
 * type `im` and let completion menu appear. It should list:
   - `im~               Snippet`
   - `import statement~ Snippet`
 * type 2 x `ctrl-j` to select `import statement~ Snippet`
 * type `<CR>`
 * you should see `import {  } from "module";` and the cursor is at the `e` of `"module"`.
 * type `i` and let completion appear
 * type `ctrl-j` and then `ctrl-k` again to select and unselect the first item
 * type `<TAB>`

**Result:** TAB character was inserted so I see `import {  } from "i     ";` with cursor before `";`

**Expected:** cursor should jump to next snippet placeholder like in this example

![vim-cmp-vsnip-working](https://user-images.githubusercontent.com/675062/185669989-e9b922de-a6b3-4453-b966-0369d8507c08.gif)

**Comment by mikehaertl** [comment]
More observations:

* The completion menu must contain items that contain a `-`, `/`, `#` or a space character
* I have to "touch" one of these items once. That means I have to select/unselect it (`cmp.mapping.select_next_item()` / `select_prev_item()`). I don't have to confirm the item.
* After that whenever I confirm something the vsnip session is broken and `TAB` doesn't jump to the next placeholder
* If I don't touch (i.e. select/unselect) any of these items in the menu it works

**Comment by hrsh7th** [comment]
Fixed https://github.com/hrsh7th/vim-vsnip/commit/b2caf50a6e3c021c92b236abff70bbb467bce24f
