### ISSUE TITLE
expand wrong for `$`

### ISSUE THREAD

**Issue by Shane-XB-Qian** [hrsh7th/vim-vsnip#274]
supposed this is the right place for this:
for example `"sed ${1|-E,--regexp-extended|} ':${2:x} N $! b$2 ${3:command}' ${4:file}"`
seems cannot expand `$!`, as well as `$$` and `$n` if n > 9 e.g `$10`

**Comment by Shane-XB-Qian** [comment]
or actually in some langs $n has special meaning too, how to make it not expand (if chose)?

**Comment by uga-rosa** [comment]
`$` as a mere symbol, it should be escaped with `\`.
```
sed ${1|-E,--regexp-extended|} ':${2:x} N \$! b$2 ${3:command}' ${4:file}
```
Also, a bug that prevented more than 10 press holders from working has recently been fixed.

**Comment by Shane-XB-Qian** [comment]
> should be escaped with `\`

looks double `\` required.

> a bug that prevented more than 9 press holders from working has recently been fixed.

thanks, good news.

**Comment by uga-rosa** [comment]
The need for two `\` is an escape in double quotes in the vim script, and the string that is actually conveyed to vsnip is `\$`. Single quotes would be one.

**Comment by Shane-XB-Qian** [comment]
ok, my case actually was from typescript, 
but vsnip was wrote by vim script, guess eventually it got was `\$`.
