### ISSUE TITLE
Escape backslash?

### ISSUE THREAD

**Issue by habamax** [hrsh7th/vim-vsnip#28]
Is it possible to escape backslashes?

```
	"Test": {
		"prefix": ["test"],
		"body": [
			"Test\\nShould be on a single line$0"
		],
		"description": ""
	}
```

I would like `Test` snippet to be expanded to:

```
Test\nShould be on a single line
```

But I get error like:
![image](https://user-images.githubusercontent.com/234774/72203600-b7a83800-347e-11ea-9081-e4830e59b242.png)

**Comment by hrsh7th** [comment]
You can use `Test\\\\nShould be on a single line$0`.
`backslash` is special character in `JSON` and `snippet` both.

**Comment by habamax** [comment]
Thank you! 

Funnily enough I tried `\\n` and `\\\n` -- I was close :).

PS

Finally I have tried your plugin and it is awesome!

I have used ultisnips for several years but it turned out that it slows down
my vim in insert mode especially when you type Russian.
