### ISSUE TITLE
Read &runtime/snippets/*.json

### ISSUE THREAD

**Issue by kitagry** [hrsh7th/vim-vsnip#31]
Hi, @hrsh7th. Thank you for nice plugin.
I would like to use existing vscode snippets. And, I don't want to install unnecessary files. So, I created [repository which includes only snippets](https://github.com/kitagry/vs-snippets). 
But, vsnip doesn't load &runtimepath/snippets/*.json. So, users should write `g:vsnip_snippet_dirs` for the path. If you like this idea, wouldn't you change vsnip to load these?

If you don't like this idea, Please close this issue.
Thank you!

**Comment by hrsh7th** [comment]
Thanks for your request.

Currently, vim-vsnip has two ways to load snippets.

1. `let g:vsnip_snippet_dirs` or `let g:vsnip_snippet_dir`
- vsnip expects the dir contains `&filetype.json` files.
- if editing `typescript.ts`, vsnip will search each dirs for `typescript.json`.

2. VSCode style snippet directory in &runtimepath
- vsnip expects &runtimepath contains `package.json`.
- The package.json must have `contributes.snippets[number].{language,path}` keys.

So you can choose below ways.

1. Put `package.json` to your repository
2. Put `plugin/your_snippet.vim` that contains `let g:vsnip_snippet_dirs += ['your snippet path']`

If you don't satisfaction the ways, could you explain the reason for it, thank.

**Comment by kitagry** [comment]
Thank you for the explanation.

Ok.. I would set a g:vsnip_snippet_dirs.
Thanks!
