### ISSUE TITLE
Add the ability to escape $ character

### ISSUE THREAD

**Issue by Shatur95** [hrsh7th/vim-vsnip#36]
In some situations, this symbol may be used in the snippet itself. For example, in the [asynctasks](https://github.com/skywind3000/asynctasks.vim) plugin use this symbol for variables (snippets very useful to generate common tasks with custom arguments).
In VSCode, [this character is treated as a snippet argument only if it is followed by `{}`](https://github.com/Microsoft/vscode/issues/1670). Is it possible to add the same behavior for compatibility?

**Comment by hrsh7th** [comment]
I pinned related issue https://github.com/hrsh7th/vim-vsnip/issues/28.
You can use \\$ in snippet.

**Comment by Shatur95** [comment]
Missed it, thank you!
