### ISSUE TITLE
Snippet deactivated after nested completion

### ISSUE THREAD

**Issue by Shatur95** [hrsh7th/vim-vsnip#37]
**Steps to reproduce:**
1. Download [akd](https://github.com/Shatur95/akd) (small project with few files, just for example)
2. Open `main.cpp`.
3. Add `#include <algorithm>`.
4. type `std::string test;`.
5. Try to pass it into `std::generate`. This function accept iterators. If I pass just `test` - snippet will not deactivated. But if I pass `test.begin()` iterator - snippet will be deactivated.

Tested with `asyncomplete` and `vim-lsp`.

**Video:**
[![asciicast](https://asciinema.org/a/KTmuXv51AUMJnvrv3wmvTEzNm.svg)](https://asciinema.org/a/KTmuXv51AUMJnvrv3wmvTEzNm)

**vsnip configuration:**
```vim
let g:vsnip_snippet_dir = expand('~/.config/nvim/vsnip')
let g:vsnip_integ_config = {}
let g:vsnip_integ_config.auto_expand = v:true

imap <expr> <Tab> pumvisible() ? '<Down>' : vsnip#available(1) ? '<Plug>(vsnip-jump-next)' : '<Tab>'
smap <expr> <Tab> pumvisible() ? '<Down>' : vsnip#available(1) ? '<Plug>(vsnip-jump-next)' : '<Tab>'
imap <expr> <C-Tab> pumvisible() ? '<Up>' : '<Plug>(vsnip-jump-prev)'
smap <expr> <C-Tab> pumvisible() ? '<Up>' : '<Plug>(vsnip-jump-prev)'
```

**Comment by hrsh7th** [comment]
Yes.
Snippet session stack is not supported now.

**Comment by Shatur95** [comment]
Would be nice to see this feature, often needed. Without it, I first have to go through all the options for the snippet and insert the object where I will call the function, and then call the functions in them.

**Comment by hrsh7th** [comment]
PR are welcome.
I will try to implement this feature but it is bit difficult so probably take a time.

**Comment by Shatur95** [comment]
I would really like to help, but I'm very new to Vim script :(

**Comment by hrsh7th** [comment]
I have started to try to implement it...

It is the gate of hell 😂

**Comment by hrsh7th** [comment]
I found the approach.
We should insert AST and organize placeholder's order instead of stack management.

**Comment by hrsh7th** [comment]
@Shatur95 could you test with #38?
It is works anyway.

**Comment by hrsh7th** [comment]
Sorry... It has bug. Please wait a moment.

**Comment by hrsh7th** [comment]
Fixed.

**Comment by hrsh7th** [comment]
@Shatur95 I've implemented it maybe.
Could you test it?

**Comment by hrsh7th** [comment]
It was tough works.
But I enjoyed implementing it and it will be very useful feature.
Thanks you for reporting issue.

**Comment by hrsh7th** [comment]
If you get more improvement point, please report it.

**Comment by Shatur95** [comment]
Thank you a lot! Just works as expected!
