### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by pwntester** [hrsh7th/vim-vsnip#4]
Hi, thanks for the plugin, I think the following features would be very interesting:
- deoplete integration
- search for plugin in runtime path so plugin developers can add snippets in their plugins
- integration with neovim built-in LSP client (lua)

**Comment by hrsh7th** [comment]
Thanks!
I planning to create `vim-vsnip-integ` repo that will contains some integration codes.

runtimepath detection is nice idea.
I want to support vscode-extension directly.

For example.

```viml
Plug 'microsoft/vscode-python'
```

Currently nvim lsp seems has no integration point to snippet support...

**Comment by hrsh7th** [comment]
My plan.

- [ ] Create `vim-vsnip-integ` repo
    - [ ] deoplete integration
    - [ ] Update README.md and doc.
- [ ] VSCode extensions snippet detection in rtp.

**Comment by pwntester** [comment]
Tried the deoplete integration but could not get it working. Is there anything needed apart from installing the plugin (with the deoplete source)?

I have the following in snippet test in my global.json file (at `let g:vsnip_snippet_dir = "~/dotfiles/snippets"`):

```
{
  "foo": {
    "prefix": "foo",
    "body": [
        "FOO $1"
    ],
    "description": "FOO TEST."
  }
}
```

Entering `foo` does not offer any snippet expansion

**Comment by hrsh7th** [comment]
Thanks for try it!

I've added `.vimrc` file.
I got right results with it.

If you don't get right results, please give the more info e.g.) vim version, your vimrc etc...

**Comment by hrsh7th** [comment]
The minimal vimrc is here.
https://github.com/hrsh7th/vim-vsnip/blob/master/.vimrc

**Comment by pwntester** [comment]
Thanks for the quick response. I tried your minimal vimrc + `let g:vsnip_snippet_dir = "~/dotfiles/snippets"` with the same results. Im using latest neovim (`NVIM v0.5.0-nightly-588-g36d1335a6`).

im getting the following output when running `UpdateRemotePlugins`:

```
remote/host: python3 host registered plugins ['deoplete']                                                                                                     remote/host: generated rplugin manifest: /Users/pwntester/.local/share/nvim/rplugin.vim
```

Should I see `vim-vsnip-integ` as well?

My dotfiles are located here: https://github.com/pwntester/dotfiles/tree/master/config/nvim

**Comment by hrsh7th** [comment]
I understood the problem.
vim-vsnip used `resolve()` in `autoload/vsnip/source.vim`.
But it seems not expand `~/dotfiles/snippets` to `/home/pwntester/dotfiles/snippets`.

I've change the `resolve` to using `expand`.
Please try it.

**Comment by pwntester** [comment]
oh my fault then, I assume it was expanded.

After upgrading I can see the option in the deoplete menu and the snippets, get expanded.

I have some problems with tabstops though, will file a different defect for it, thanks!

**Comment by hrsh7th** [comment]
I've implemented `Detect VSCode snippets in rtp.` feature.
If you have anytime, please try it.

**Comment by pwntester** [comment]
Jus tried it and works great for me, thanks!

**Comment by hrsh7th** [comment]
Thanks for your idea! its useful for me too.
