### ISSUE TITLE
Snippets can be overwritten with LSP

### ISSUE THREAD

**Issue by Shatur95** [hrsh7th/vim-vsnip#40]
If I have a snippet with the same name as the LSP completion item, the snippet will not be displayed in the list of auto-completion items.
**Steps to reproduce:**
1. Create the following snippet
```json
{
  "test": {
    "prefix": ["set"],
    "body": [
      "set test ${1:element}"
    ],
    "description": "test"
  }
}
```

2. Open .vim file with vim-language-server enabled.
3. Type "se".

**Actual behavior:**
Auto-completion show only "set" completion from LSP.

**Expected behavior:**
Auto-completion show "set" from LSP and "set" from vim-vsnip.

**Note:**
If you change snippet name to something like "mysnippet", auto-completion will show it. I have the same issue with `clangd` that shows functions with the same names (but with different overloads). It would be very useful to add snippets with the same nave (like snippet overloads). For example, C++ have two `for` loops, range-based and index-based. Also `clangd` provides only one `for` snippet that is not very useful and I would like to create my own.
Is it even possible to fix? And is this the right place for the issue?
I tested it in asyncomplete and vim-lsp.

**Comment by hrsh7th** [comment]
Fixed in https://github.com/hrsh7th/vim-vsnip-integ/commit/dc2a04141aa69cd4eefd6e1602b386d8428ac9de

**Comment by Shatur95** [comment]
Thank you a lot for the fix and compete integration.

Is it possible to specify vsnip snippets priority? To show vsnip snippets first, than show LSP completions. Or this is completion plugin depended?
