### ISSUE TITLE
Add snippets preview

### ISSUE THREAD

**Issue by Shatur95** [hrsh7th/vim-vsnip#41]
I would like to suggest to add a preview for snippets. Is it possible? For example, QtCreator have this feature:
![изображение](https://user-images.githubusercontent.com/22453358/77226665-c13ad400-6b82-11ea-8726-243a1a47f570.png)

P.S. Sorry for a lot of issues :)

**Comment by hrsh7th** [comment]
vsnip can't support preview featute.
It should implented in completion plugin.

**Comment by Shatur95** [comment]
Yes, I understand that vsnip cannot display a preview, but can it provide information about it in order to display it in a completion plugin (as it displays function information)?

**Comment by hrsh7th** [comment]
I don't understand your mean.

For example, vim-compete can support preview and compete-vsni-source can provide preview information but vsnip deos nothing to support it.

**Comment by Shatur95** [comment]
Got it, thanks! For some reason I thought that source provides vsnip itself.

**Comment by hrsh7th** [comment]
You should create issue to vim-compete to support preview feature.

**Comment by Shatur95** [comment]
Do I understand correctly that this should be in [vim-compete](https://github.com/hrsh7th/vim-compete), and not in [vim-vsnip-integ](https://github.com/hrsh7th/vim-vsnip-integ) to provide snippets preview in vim-compete?
