### ISSUE TITLE
Snippet expansion in clangd headers

### ISSUE THREAD

**Issue by Shatur95** [hrsh7th/vim-vsnip#42]
When I `#include <header>` snippet (provided by `clangd`) it suggest headers with `>`. So, when i using autocomplete I have one extra symbol inserted. Is it `vim-vsnip` issue?
[![asciicast](https://asciinema.org/a/ixhYyO6FN24RwIBjXSeXN5Yaw.svg)](https://asciinema.org/a/ixhYyO6FN24RwIBjXSeXN5Yaw)

**Comment by hrsh7th** [comment]
I was reproduce it.

I investigate it please wait.

**Comment by hrsh7th** [comment]
@Shatur95 Sorry, it was the `vim-lamp`'s probolem.

**Comment by hrsh7th** [comment]
@Shatur95 Fixed in https://github.com/hrsh7th/vim-lamp/commit/b291b42bbe96805bbb59872a4eb87d3db967745f

**Comment by Shatur95** [comment]
Thank you!
