### ISSUE TITLE
[Question] How to call s:jump(1) from vimrc?

### ISSUE THREAD

**Issue by ryuta69** [hrsh7th/vim-vsnip#43]
Thank you for this great plugin.

I like to map the same key with deoplete and ultisnips, and I succeeded with Expand like below. (I map enter to expand.)

```vim
fun! DeoEnter()
        if vsnip#available(1)
                call vsnip#expand()
                return "\<c-y>"
        endif

        call UltiSnips#ExpandSnippetOrJump()
        if g:ulti_expand_or_jump_res > 0
                return ""
        endif

        if pumvisible()
                return "\<c-y> "
        endif

        return "\n"
endfun
ino <CR> <C-R>=DeoEnter()<CR>
```

However, I couldn't achieve to Jump because I have no idea to call s:jump(1) from vimrc. Below is my try.

```vim
fun! DeoTab()
        if vsnip#available(1)
                "" I want to call s:jump(1) here.
                return ""
        endif

        if pumvisible()
                return "\<C-n> "
        endif

        return "\<Tab>"
endfun
ino <Tab> <C-R>=DeoTab()<CR>
```

Do you have an any idea?

I've found this article https://groups.google.com/forum/#!topic/vim_use/bUE3yaAQXRc, and it shows like

```vim
" referencee.vim:
    function Scope()
      return s:
    endfunction
    let s:mile = 'XD'

" referencer.vim:
    let s = Scope()
    echo s['mile']
    " ==> 'XD'
```

From above, I think it's good to offer scope from plugin maybe...? If it's good to you, I will send PR.

**Comment by hrsh7th** [comment]
I think we should implement `vsnip#jump(direction)`.

I will implement it.

BTW, Your setting is very interesting. I couldn't think to use vsnip and ultisnips both.

I was just curious, Why you use both?

**Comment by ryuta69** [comment]
Oh, that sounds great.

> Why you use both?

I prepare two kinds of snippets, 

- Basic minimal snippets (such as `if`, `class`)
- My extended snippets that are long or for niche purposes, thus usual snippets library doesn't support (such as `erase a certain char from string`, `dfs`) ([example](https://github.com/ryuta69/dotfiles/commit/eec5fde2ba429751c102fea86a285179b49702f7))

I use Ultisnips and vim-snippets as former, and your vsnip as latter.

The reason why I chose your vsnip is that I had always tried to share snippets with vscode and vim, but it was a hell of tasks. There was a once time that I gave up and move all snippets into Alfred, but not my like. Then I found your plugin **really great and this is what I've been looking for**.

**Comment by ryuta69** [comment]
UPDATE:

I accomplished without changing. When I created an issue, I didn't know how to exec plug command at insert mode.

```vim
let g:ulti_expand_or_jump_res = 0
let g:UltiSnipsExpandTrigger='<NUL>'
let g:UltiSnipsJumpForwardTrigger='<Tab>'
let g:UltiSnipsJumpBackwardTrigger='<S-Tab>'
fun! DeoEnter()
        if pumvisible()
                if vsnip#available(1)
                        call vsnip#expand()
                        return "\<C-y>"
                endif

                call UltiSnips#ExpandSnippetOrJump()
                if g:ulti_expand_or_jump_res > 0
                        return ""
                endif

                return "\<C-y>"
        endif

        return "\n"
endfun
ino <CR> <C-R>=DeoEnter()<CR>
fun! DeoTab()
        if vsnip#available(1)
                return "\<Plug>(vsnip-jump-next)"
        endif

        if pumvisible()
                return "\<C-n>"
        endif

        return "\<Tab>"
endfun
imap <expr> <Tab> DeoTab()
smap <expr> <Tab> DeoTab()
fun! DeoShiftTab()
        if vsnip#available(-1)
                return "\<Plug>(vsnip-jump-prev)"
        endif

        if pumvisible()
                return "\<C-p>"
        endif

        return "\<S-Tab>"
endfun
imap <expr> <Tab> DeoShiftTab()
smap <expr> <Tab> DeoShiftTab()
```

**Comment by hrsh7th** [comment]
Sorry for my delay...

It's nice that the problem has been fixed.

**Comment by ryuta69** [comment]
No way, it's just my personal want and really kind of you to say that. Thank you very much again.
