### ISSUE TITLE
Question: using snippets from vscode plugins

### ISSUE THREAD

**Issue by urandom** [hrsh7th/vim-vsnip#46]
Hi,

The readme states that one can seemingly use snippets defined from vscode plugins.
As written, I've added `    Plug 'microsoft/vscode-go'` to my init.vim file, though I don't know how to trigger the expansion of a snippet prefix to an actual snippet.

If i write `iferr` - a prefix defined in the abovementioned vscode plugin, how do I go about turning it into actual code afterwards?

**Comment by hrsh7th** [comment]
It seems the problem by vsnip.

I have missed the https://github.com/microsoft/vscode-go/blob/master/snippets/go.json#L2 snippet format.

We should support it.
Thank you for reporting.

**Comment by hrsh7th** [comment]
It seems to relate to here (https://github.com/microsoft/vscode/blob/0ba9f6631daec96a2b71eeb337e29f50dd21c7e1/src/vs/workbench/contrib/snippets/browser/snippetsFile.ts#L216).

I will implement it.

**Comment by hrsh7th** [comment]
I've fixed the issue! Thank you for reporting it.
