### ISSUE TITLE
E212: Can't open file for writing

### ISSUE THREAD

**Issue by hhaoao** [hrsh7th/vim-vsnip#52]
system: windows 10

repetition:  After installing the plug-in, use the "VsnipOpe" command in vim as required by `Readme`. 

I've created a directory of "~\\.vsnip" and everything is fine.

**Comment by hrsh7th** [comment]
Thank you for your report.

I think it would be good to prompt `g:vsnip_snippet_dir does not exists, create?> y/n` for user.
Do you think about it?

**Comment by hhaoao** [comment]
Sorry, I didn’t reply so late, I think your idea is good, but I personally prefer the plugin author to provide me with some default settings. If one day I change my mind, I only need to modify my favorite options based on the documentation.

**Comment by hrsh7th** [comment]
Hm... Is your means we should create with no prompt the default directory?

**Comment by hhaoao** [comment]
Yes, I think this is not a bad idea. The highly recognizable directory naming is to ensure that this approach is not cursed (bad naming:'config','setting').

**Comment by hrsh7th** [comment]
Currently, vsnip provides default value as `let g:vsnip_snippet_dir = expand('~/.vsnip')`.

So I think we would be good to care about the only case of the directory that does not exist.

I tried to improve it by https://github.com/hrsh7th/vim-vsnip/commit/eea69f74c4d4bc11ed73416ab8f9cabc59b743bd

Some users are worried that they will hate creating directories on their own.
