### ISSUE TITLE
Bug: Can't enable vsnip when some snippet exists

### ISSUE THREAD

**Issue by ryuta69** [hrsh7th/vim-vsnip#54]
## about

Can't enable vsnip when some snippet exists.

 NVIM v0.4.3
 deoplete latest at 2020/07/17
 vsnip    latest at 2020/07/17

## minimal repro

in python.json

```python
{
	"Quicksort": {
		"prefix": ["quicksort"],
		"body": [
			"def quicksort(l):",
			"	if len(l) <= 1:",
			"		return l",
			"	else:",
   			"	    pivot = l.pop()",
   			"	    greater, lesser = [], []",
   			"	    for el in l:",
   			"	        if el > pivot:",
   			"	            greater.append(el)",
   			"	        else:",
   			"	            lesser.append(el)",
   			"	    return quicksort(lesser) + [pivot] + quicksort(greater)"
		]
	}
}
```

with this, vsnip doesn't run nor show all other snippets in deoplete.

....However, below works.

```python
{
	"Quicksort": {
		"prefix": ["quicksort"],
		"body": [
			"def quicksort(l):"
		]
	}
}
```

I thought maybe `:` in last sentence makes wrong, but not. Below works.

```python
	"Def": {
		"prefix": ["def"],
		"body": [
			"def ${1:defname}($2):",
			"    $0"
		]
	}
```

Any suggestion is appreciated. I look into code but couldn't find any causes...

**Comment by hrsh7th** [comment]
Hi, @ryuta69.

Your snippet seems to have tab character but JSON needs `\t` character.

**Comment by ryuta69** [comment]
@hrsh7th 
Thank you it fixed!

...Actually it works in VSCode, so I didn't know about that json_encode of vim can't work with tab.

https://github.com/neovim/neovim/issues/7058

Would it be better to add an either of features below?

1. Show error about this. `vsnip#source#create` won't alert because it works as json. `get_complete_items` is good place to alert.
2. Replace tab into '\t' in body.

If it's ok to you, I will create PR. 
If it's not fine, I will close this.

**Comment by hrsh7th** [comment]
Oh... VSCode...

I will try `substitute(join(l:body, "\n"), '\t', '\\t', 'g')` 😂

**Comment by ryuta69** [comment]
lol~

I just was afraid if you care about performance and gonna say "you can sed". Okey, gonna try that one.

**Comment by ryuta69** [comment]
it's just slow and I think it shouldn't be handled in vsnip, so I will close.

Thank you for your reply!

**Comment by hrsh7th** [comment]
Thank you for your report.
I will consider to solve it in vsnip side.
