### ISSUE TITLE
Provide a default value for TM_SELECTED_TEXT

### ISSUE THREAD

**Issue by jandamm** [hrsh7th/vim-vsnip#56]
Using `${TM_SELECTED_TEXT:abc}` in a snippet, I would expect `abc` to be inserted when I haven't selected any text.
Instead `''` (empty string) is inserted.

Is this an issue with Vsnips or is this the expected behavior from VSCode?

**Comment by hrsh7th** [comment]
This is vsnip problem.
I will fix it.

**Comment by hrsh7th** [comment]
Fixed in https://github.com/hrsh7th/vim-vsnip/commit/e7a8ea7471dbbe2d54b737ad073e7c315c905176
