### ISSUE TITLE
Jump vs Expand

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/vim-vsnip#6]
Currently implementation says "prefer jump than expand".
But it is not expected spec (just implementation).

I think vsnip should use expand instead of jump.

**Comment by pwntester** [comment]
Is it possible to use different mappings for expanding and jumping? It would be great to be able to expand with <tab> for example, but then move around the tabstops forward and backwards with <c-j> and <c-k>

Thanks

**Comment by hrsh7th** [comment]
OK, I will implement separate mapping.
backward jump is able to implement maybe. I will try it.

**Comment by hrsh7th** [comment]
Implemented in #13

**Comment by hrsh7th** [comment]
I supporting this with backward jump feature.
But it needs re-design some apis.
Re-design is bit difficult(I'm confusing).

**Comment by hrsh7th** [comment]
Closed in #13.
