### ISSUE TITLE
Improve internal variable handling

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/vim-vsnip#61]
Currently, vsnip does convert variable-node to text-node when initializing snippet.

I think we should change this approach to the below.

1. Don't convert variable-node to text-node
2. Support `transform` feature that defined in spec
3. Add ability to customize variable-resolver (builtin variables should be realized by it)

**Comment by hrsh7th** [comment]
http://speakingjs.com/es5/ch19.html

**Comment by aca** [comment]
This is great. What's your plan to support js regex with vimscript?

**Comment by hrsh7th** [comment]
I'm busy now but if I get free time, I try to support it.

1. Cistom variable register I/F
2. Support JS regex

**Comment by hrsh7th** [comment]
I plan to make this, but I think no one will use this feature 😂

**Comment by aca** [comment]
@hrsh7th I will!. Curious how you will solve it. 

Thanks for the great plugin by the way.

**Comment by hrsh7th** [comment]
I'm planning

- Parse JavaScript regular expression
- Convert Vim regular expression from AST
- Call `matchlist` and replace all captured back reference

**Comment by hrsh7th** [comment]
Duplicate https://github.com/hrsh7th/vim-vsnip/issues/83
