### ISSUE TITLE
Is it possible to use # in "prefix"?

### ISSUE THREAD

**Issue by jandamm** [hrsh7th/vim-vsnip#62]
I would like `#env` to expand to `#!/usr/bin/env ...`.
I haven't found a way to escape the `#` yet.
Is this possible? 

Somewhat related to #36

**Comment by hrsh7th** [comment]
Thank you for your reporting.

It seems a bug of vsnip.
I will fix it.

**Comment by hrsh7th** [comment]
I sent the PR to fix the problem.

Could you test it?

**Comment by jandamm** [comment]
Yes, it works fine for me 👍
