### ISSUE TITLE
compatibility with older vim?

### ISSUE THREAD

**Issue by mg979** [hrsh7th/vim-vsnip#7]
Is there a reason why it's using `getbufline()` and related functions, instead of `getline()`?
Are there cases where the working buffer is not the current buffer?

**Comment by hrsh7th** [comment]
I want to work in older vim too.
But 'deletebufline' can not replace to compatible code, I think. (appendbufline is replaceable to append...)

**Comment by hrsh7th** [comment]
> Are there cases where the working buffer is not the current buffer?
I think cursor is always on the working buffer.

**Comment by mg979** [comment]
Instead of `deletebufline()` you can use delete, example:

    call deletebulfine(bufnr, start, end)

becomes (using `:delete` and a range)

    exe start . ',' . end . 'delete _'

where `_` means to the black hole register (so that no registers are overwritten).

**Comment by hrsh7th** [comment]
Thanks. I try it.

**Comment by hrsh7th** [comment]
Thanks.

I've supported older vim!
