### ISSUE TITLE
Can't escape \n

### ISSUE THREAD

**Issue by ryuta69** [hrsh7th/vim-vsnip#72]
minimal reproduce
```
	"PrintArrayWithBreak": {
		"prefix": ["printarraywithbreak"],
		"body": [
			"print($1, sep='\\n')$0"
		]
	},

    # ideal output that vscode does
    # print(, sep='\n') 

    # Actual output
    # print(, sep='n') 
```

I thought it can be fixed here, 
```
# autoload/vsnip.vim
function! vsnip#get_context() abort
  let l:before_text = getline('.')[0 : col('.') - 2]
  for l:source in vsnip#source#find(&filetype)
    for l:snippet in l:source
      for l:prefix in (l:snippet.prefix + l:snippet.prefix_alias)
        let l:match = matchlist(l:before_text, printf('\%(\(\k\+\)\V%s\m\)\=\<\(\V%s\m\)\>$',
              \   escape(g:vsnip_auto_select_trigger, '\'),
              \   escape(l:prefix, '\'),
              \ ))

```

but sorry, I can't understand the `\%(\(\k\+\)\V%s\m\)\=\<\(\V%s\m\)\>$` part... so I couldn't fix.
Do you think it's able to fix?

**Comment by hrsh7th** [comment]
Thank you for your report.

Hm... it seems different escaping interpretation between vscode and vsnip.

Anyway, you can use double escape `"print($1, sep='\\\\n')$0"`.

But I want to align behavior for vscode so I investigate what is vscode does.

**Comment by ryuta69** [comment]
Wow it works.
Not only vim, but also vscode.

https://github.com/microsoft/vscode/issues/32020#issuecomment-323775984

I don't know how vscode handle this, but the issue related to this looks messy. 

Anyway thank you for your response and great plugin, again.

**Comment by hrsh7th** [comment]
It seems vsnip does not respect spec.

**Comment by hrsh7th** [comment]
I've fixed in #73.
Could you test it?

**Comment by ryuta69** [comment]
@hrsh7th 
It works as VSCode! Thank you very much for your great work.

<img width="651" alt="ss 1" src="https://user-images.githubusercontent.com/41639488/89281106-8abeab00-d684-11ea-88ed-66c6f0219586.png">

**Comment by hrsh7th** [comment]
Yeah! Thank you for your report!
