### ISSUE TITLE
tests running when loading vim

### ISSUE THREAD

**Issue by prabirshrestha** [hrsh7th/vim-vsnip#78]
![image](https://user-images.githubusercontent.com/287744/89482742-5e239580-d74f-11ea-93ce-c94aac98af39.png)

seems like flies in plugin folder is getting autloaded.

**Comment by hrsh7th** [comment]
Thank you for reporting... It should be fixed now.

**Comment by prabirshrestha** [comment]
thanks for the quick temp fix.
