### ISSUE TITLE
Coc support?

### ISSUE THREAD

**Issue by glepnir** [hrsh7th/vim-vsnip#80]
As title

**Comment by hrsh7th** [comment]
I think the coc already has a snippet feature that is powerful than vsnip...

If you still need to support, please explain what is the reason.

**Comment by glepnir** [comment]
I saw the introduction of vsnip `similar to vscode`. I thought that vsnip implemented a code snippet similar to vscode multi-cursor.if there is not. close this issue

**Comment by hrsh7th** [comment]
Does the coc has no multi-cursor(mirror)? I will investigate it.

**Comment by glepnir** [comment]
Coc provides multiple cursors, but not in coc-snippet.

**Comment by hrsh7th** [comment]
1. coc-snippet has supporting to mirror placeholders.
2. vsnip does not support multi cursors.
