### ISSUE TITLE
How to use the same snippets for different filetypes?

### ISSUE THREAD

**Issue by ahmedelgabri** [hrsh7th/vim-vsnip#81]
I'm trying to see if I can migrate from UltiSnips & in UltiSnips you can extend multiple snippets to be included for the current filetype you have. For example:

`html.snippets`

```
snippet html
<!DOCTYPE html>
<html>
	<head>
		<title>${1:Title}</title>
		<meta charset="utf8">
		<meta name="viewport" content="initial-scale=1, width=device-width">
		<link rel="stylesheet" href="${2:style.css}">
	</head>
	<body>
		$0
		<script src="${3:bundle.js}"></script>
	</body>
</html>
endsnippet
```

`jinja.snippets`

```
extend html 

snippet for
{% for ${1} in ${2} %}
	${0:${VISUAL}}
{% endfor %}
endsnippet
```

I can also do this for `django` templating since it is nearly identical to jinja

`htmldjango.snippets`

```
extend html, jinja
```

or 

```
extend jinja
```

Can this be done or not? (I assume no, but wanted to check)

**Comment by hrsh7th** [comment]
Currently, vsnip does not support it.

My random thought is it would be good to provide `g:vsnip_filetypes` variable.

```viml
let g:vsnip_filetypes = {}
let g:vsnip_filetypes.typescriptreact = ['typescript', 'javascript']
let g:vsnip_filetypes.jinja = ['html']
```

**Comment by hrsh7th** [comment]
(I am not a native English speaker so every naming is hard and worry to decision...)

**Comment by ahmedelgabri** [comment]
I think this is a good idea 👍

**Comment by ahmedelgabri** [comment]
Another question, is there is something similar to `all.snippets` in UltiSnips in vsnip? can this be fixed by the above solution?

For example

```vim
let g:vsnip_filetypes = {}
let g:vsnip_filetypes.['*']= ['all']
```

**Comment by hrsh7th** [comment]
I think vsnip's `global.json` is the same feature for ultisnips's all.snippets.

If these does not the same, please explain what you want.

**Comment by hrsh7th** [comment]
Implemented in #89

**Comment by ahmedelgabri** [comment]
Working great, thanks @hrsh7th!

**Comment by jandamm** [comment]
Unfortunately this breaks the Vim way to handle sub filetypes.
In vim you would typically solve this by setting the filetype to `jinja.html`.

This is also the way how UltiSnips handles this.
Using filetypes with a `.` to separate them is supported by many other plugins as well.

**Comment by hrsh7th** [comment]
I intentionally deleted it, but I think it's OK to restore it.

For example, `javascript.tsx` case, how we should handle it?

1. filetypes=`javascript.tsx`, `javascript`, `tsx` and `g:vsnip_filetypes['javascript.tsx']`
2. filetypes=`javascript`, `tsx` and `g:vsnip_filetypes['javascript.tsx']`
3. filetypes=`javascript`, `tsx` and `g:vsnip_filetypes['javascript']` + `g:vsnip_filetypes['tsx']`

**Comment by jandamm** [comment]
Using the "Vim-logic" it would check in `javascript.json` and `tsx.json`.
When the prefix is available in both, the `javascript` one is used, as it is the first filetype.

**Comment by hrsh7th** [comment]
Due to my previous decision, probably we can not able to ignore`javascript.tsx.json`... sorry.

But thank you! your opinion seems correct to me.

I restore it as `javascript.tsx`, `javascript`, `tsx` and `g:vsnip_filetypes['javascript.tsx']`.

**Comment by hrsh7th** [comment]
Hm... How to change this behavior with keeping backward compatibility.

**Comment by jandamm** [comment]
What if this would prefill `g:vsnip_filetypes['javascript.tsx'] = ['javascript', 'tsx']`?
Of course only if the key does not exist.

**Comment by jandamm** [comment]
This would let the user decide if the default behavior is wanted (by not doing anything) or overwrite it with its own logic.

**Comment by hrsh7th** [comment]
Ah. sorry.
I was misunderstanding the previous behavior.

I was checked `VsnipOpen` command after `set filetype=javascript.jsx` in old vsnip.
Then, vsnip display `javascript` or `jsx` or `global`.

So we has no problem maybe.

**Comment by hrsh7th** [comment]
I think https://github.com/hrsh7th/vim-vsnip/pull/96/files solves this problem.

**Comment by jandamm** [comment]
Looks good 👍

**Comment by hrsh7th** [comment]
Thank you!
