### ISSUE TITLE
Wrong selection when expanding snippets with placeholder values 1 character long

### ISSUE THREAD

**Issue by svermeulen** [hrsh7th/vim-vsnip#85]
Example:
```json
{
  "For Loop": {
    "prefix": ["for"],
    "body": [
      "for ${1:i}=${2:1},${3:10}",
      "\t${0:print(i)}"
    ]
  },
}
```
If this snippet is expanded, the first selection is:
![image](https://user-images.githubusercontent.com/810762/89722046-3d4e8080-d999-11ea-9879-e07ca3e029f7.png)

If it is changed to this:
```json
  "For Loop": {
    "prefix": ["for"],
    "body": [
      "for ${1:ii}=${2:11},${3:10}",
      "\t${0:print(i)}"
    ]
  },
```
Then it works fine, so it seems to be related to using a single character as a placeholder value

**Comment by hrsh7th** [comment]
Sorry, it has regression. I've fixed now.
