### ISSUE TITLE
Using same snippets for multiple filetypes

### ISSUE THREAD

**Issue by kristijanhusak** [hrsh7th/vim-vsnip#90]
Hi,

is there a way to use same snippet file for multiple filetypes?
I know I can add global snippet, but I don't need it on global level.
This is mostly for javascript/typescript, which can have 4 filetypes (javascript,typescript,javascriptreact,typescriptreact).

**Comment by Shougo** [comment]
https://github.com/hrsh7th/vim-vsnip/pull/89

You can use the feature.

**Comment by hrsh7th** [comment]
Thank you for your request and pointing it.

Yes, I think it should be supported now in #89!

**Comment by kristijanhusak** [comment]
WOrks great, thanks!
