### ISSUE TITLE
Prefix with '---' always expands

### ISSUE THREAD

**Issue by mg979** [hrsh7th/vim-vsnip#98]
I have this snippet in `global.json`

```json
    "---": {
        "description": "",
        "body": [
            "${VIM:repeat('-', &tw)}",
            "$0"
        ],
        "prefix": [
            "---"
        ]
    }
```

It always expands for every character (and with every tab press because of my mappings).

I could fix it with this:

https://github.com/mg979/vim-vsnip/commit/bdded7a285c8427b3ffa1049ca591151185ff51c

**Comment by hrsh7th** [comment]
Thank you for your report!

It a bug of `s:resolve_prefix` in the `autoload/vsnip/source.vim`.

I will fix it soon.

**Comment by hrsh7th** [comment]
Thank you! It should be fixed now.
